/**
 * POST /api/dev/create-invite
 *
 * Creates a developer invite and returns the invite link.
 * Requires an authenticated session with role admin, dev, or project_owner.
 *
 * Body:
 *   { email: string, role?: string, message?: string }
 *
 * Response:
 *   { token: string, link: string, expiresAt: string }
 *
 * Email delivery:
 *   Currently returns the link for manual sharing.
 *   To add email delivery, uncomment the Resend/email section below
 *   and set RESEND_API_KEY in your environment.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const ALLOWED_ROLES = ['admin', 'dev', 'developer', 'project_owner']

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Nicht angemeldet.' }, { status: 401 })
  }

  // Check that the caller has a permitted role.
  const { data: profile } = await supabase
    .from('profiles')
    .select('role, full_name, workspace_id')
    .eq('id', user.id)
    .maybeSingle()

  if (!profile || !ALLOWED_ROLES.includes(profile.role ?? '')) {
    return NextResponse.json({ error: 'Keine Berechtigung.' }, { status: 403 })
  }

  const body = await req.json().catch(() => null)
  const email:   string = (body?.email   ?? '').trim().toLowerCase()
  const role:    string = (body?.role    ?? 'developer').trim()
  const message: string = (body?.message ?? '').trim()

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: 'Ungültige E-Mail-Adresse.' }, { status: 400 })
  }

  // Fetch workspace name for the invite card.
  let workspaceName: string | null = null
  if (profile.workspace_id) {
    const { data: ws } = await supabase
      .from('workspaces')
      .select('name')
      .eq('id', profile.workspace_id)
      .maybeSingle()
    workspaceName = ws?.name ?? null
  }

  // Insert invite — token is auto-generated by the DB default.
  const { data: invite, error: insertErr } = await supabase
    .from('developer_invites')
    .insert({
      inviter_id:     user.id,
      inviter_name:   profile.full_name ?? user.email ?? null,
      inviter_email:  user.email ?? null,
      workspace_id:   profile.workspace_id,
      workspace_name: workspaceName,
      invited_email:  email,
      role:           role,
      message:        message || null,
    })
    .select('token, expires_at')
    .single()

  if (insertErr || !invite) {
    console.error('[create-invite]', insertErr)
    return NextResponse.json({ error: 'Einladung konnte nicht erstellt werden.' }, { status: 500 })
  }

  const origin = req.headers.get('origin') ?? 'https://festag.app'
  const link = `${origin}/dev/join/${invite.token}`

  // ── Email delivery (Resend) ──────────────────────────────────────────
  // Uncomment and configure once RESEND_API_KEY is set.
  //
  // const { Resend } = await import('resend')
  // const resend = new Resend(process.env.RESEND_API_KEY)
  // await resend.emails.send({
  //   from:    'Festag <noreply@festag.app>',
  //   to:      email,
  //   subject: `${profile.full_name ?? 'Jemand'} lädt dich als Developer bei Festag ein`,
  //   html:    buildInviteEmail({ link, inviterName: profile.full_name, workspaceName, role, message }),
  // })
  // ─────────────────────────────────────────────────────────────────────

  return NextResponse.json({
    token:     invite.token,
    link,
    expiresAt: invite.expires_at,
  })
}

// ── Email HTML template ────────────────────────────────────────────────
// Used once email delivery is enabled.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function buildInviteEmail({
  link, inviterName, workspaceName, role, message,
}: {
  link: string
  inviterName: string | null
  workspaceName: string | null
  role: string
  message: string
}) {
  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <title>Festag Developer-Einladung</title>
</head>
<body style="margin:0;padding:0;background:#000;color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,'Inter',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#000;min-height:100vh;">
    <tr><td align="center" style="padding:48px 24px;">
      <table width="520" cellpadding="0" cellspacing="0" style="background:#111114;border-radius:20px;border:1px solid rgba(255,255,255,0.08);overflow:hidden;">
        <tr><td style="padding:40px 40px 32px;border-bottom:1px solid rgba(255,255,255,0.06);">
          <img src="https://festag.app/brand/festag-mark.png" width="36" height="36" alt="Festag" style="border-radius:10px;" />
          <h1 style="margin:24px 0 8px;font-size:22px;font-weight:600;color:#f5f5f7;line-height:1.3;">
            Du wurdest als Developer eingeladen.
          </h1>
          <p style="margin:0;font-size:15px;line-height:1.6;color:rgba(245,245,247,0.55);">
            ${inviterName ?? 'Ein Festag-Administrator'} lädt dich ein,
            als ${role} bei <strong style="color:rgba(245,245,247,0.8);">${workspaceName ?? 'Festag'}</strong> mitzuarbeiten.
          </p>
        </td></tr>
        ${message ? `<tr><td style="padding:24px 40px;border-bottom:1px solid rgba(255,255,255,0.06);">
          <p style="margin:0 0 6px;font-size:11px;font-weight:500;letter-spacing:.08em;text-transform:uppercase;color:rgba(245,245,247,0.3);">Persönliche Nachricht</p>
          <p style="margin:0;font-size:14px;line-height:1.65;color:rgba(245,245,247,0.65);">${message}</p>
        </td></tr>` : ''}
        <tr><td style="padding:32px 40px 24px;">
          <a href="${link}" style="display:inline-block;background:#f5f5f7;color:#0a0a0c;font-size:15px;font-weight:500;text-decoration:none;padding:14px 28px;border-radius:12px;">
            Einladung annehmen →
          </a>
          <p style="margin:20px 0 0;font-size:12px;color:rgba(245,245,247,0.3);line-height:1.5;">
            Oder kopiere diesen Link in deinen Browser:<br/>
            <span style="color:rgba(245,245,247,0.5);word-break:break-all;">${link}</span>
          </p>
        </td></tr>
        <tr><td style="padding:20px 40px;background:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);">
          <p style="margin:0;font-size:11.5px;color:rgba(245,245,247,0.28);line-height:1.55;">
            🔒 <strong>Sicherheitshinweis:</strong> Festag fragt niemals Passwörter per E-Mail ab.
            Gültige Einladungslinks kommen ausschließlich von <strong>festag.app</strong>.
            Diese Einladung läuft nach 72 Stunden ab.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
}
