import type { DocKind } from '@/lib/documents/templates'

/** Rotating ghost prompts for the document Tagro compose bar. */
export const DOCUMENT_TAGRO_PROMPTS: Record<DocKind, string[]> = {
  angebot: [
    'Angebot für Website-Relaunch, 3 Positionen, 12.000 €, gültig 30 Tage',
    'Angebot Branding-Paket inkl. Logo und Styleguide, Festpreis 4.500 €',
    'Angebot UX-Audit und Prototyp, 2 Wochen, 6.800 € netto',
    'Angebot Shopify-Shop Setup, 8.900 €, Lieferung in 6 Wochen',
    'Angebot Social-Media-Kampagne Q3, 3.200 €, inkl. 12 Creatives',
    'Angebot SEO-Optimierung, 6 Monate, 750 € monatlich',
    'Angebot App-Design Phase 1, 14.500 €, 8 Screens inkl. Designsystem',
    'Angebot Fotoshooting Produktlinie, 1 Tag, 1.890 €',
    'Angebot Workshop Strategie, 1 Tag vor Ort, 2.400 €',
    'Angebot Wartung WordPress, 12 Monate, 120 € monatlich',
    'Angebot Landingpage für Kampagne, Festpreis 3.600 €',
    'Angebot Corporate Design Refresh, Logo, Typo, Templates, 7.200 €',
    'Angebot Video-Schnitt 60 Sek., inkl. Color Grading, 980 €',
    'Angebot E-Mail-Marketing Setup, Klavio, 2.100 €',
    'Angebot Pitch-Deck Design, 12 Folien, 1.650 €',
    'Angebot Marktforschung Interviews, 8 Gespräche, 4.800 €',
    'Angebot Performance Ads Setup, Meta und Google, 2.750 €',
    'Angebot Illustrationen Paket, 6 Motive, 2.200 €',
    'Angebot Onboarding-Flow UX, 5.400 €, 3 Wochen',
    'Angebot Jahresretainer Content, 24 Posts, 9.600 €',
  ],
  rechnung: [
    'Rechnung Projektmanagement März, 40 Stunden à 95 €, Zahlung 14 Tage',
    'Rechnung Hosting und Wartung Q2, 890 €, Leistungszeitraum April–Juni',
    'Rechnung an Müller GmbH, Entwicklung Sprint 4, 3.200 € netto',
    'Rechnung Design Sprint Februar, 24 Stunden à 110 €',
    'Rechnung Beratung Q1, Pauschal 4.500 €, fällig in 7 Tagen',
    'Rechnung Shopify-Wartung Januar, 450 €, monatlich',
    'Rechnung Fotoproduktion, Tagessatz 1.200 €, 2 Tage',
    'Rechnung Übersetzung EN-DE, 8.500 Wörter, 680 €',
    'Rechnung API-Integration, Festpreis 2.800 €',
    'Rechnung Schulung Team, 1 Tag, 1.600 €',
    'Rechnung Lizenz Software Q1, 320 €',
    'Rechnung Druckkosten Flyer, 500 Stück, 890 €',
    'Rechnung SEO-Monitoring März, Retainer 650 €',
    'Rechnung Video-Produktion, 45 Sek., 3.400 €',
    'Rechnung Konzeption App, Meilenstein 2, 6.000 €',
    'Rechnung Support-Paket, 10 Tickets, 750 €',
    'Rechnung Domain und SSL, Jahresgebühr 180 €',
    'Rechnung Copywriting Website, 12 Seiten, 2.160 €',
    'Rechnung Analytics Setup, einmalig 980 €',
    'Rechnung Abschluss Website-Relaunch, Restbetrag 8.500 €',
  ],
  vertrag: [
    'Dienstleistungsvertrag UX-Design, 6 Monate, Festpreis 18.000 €',
    'Wartungsvertrag Webshop, monatlich 450 €, 12 Monate Laufzeit',
    'Vertrag App-Entwicklung Phase 1, Meilensteine, 24.000 € gesamt',
    'Rahmenvertrag Marketing, 12 Monate, monatlich 2.800 €',
    'Vertrag NDA und Beratung, 24 Monate, Stundensatz 120 €',
    'Projektvertrag Branding, 8 Wochen, 9.500 €, 2 Revisionen',
    'Supportvertrag SLA 24h, 350 € monatlich, 12 Monate',
    'Vertrag Content-Produktion, 4 Videos pro Quartal, 6.400 €',
    'Freelancer-Vertrag Entwicklung, 3 Monate, 80 Stunden',
    'Vertrag Hosting und Betrieb, jährlich 1.980 €',
    'Werkvertrag Landingpage, Festpreis 5.200 €, Abnahme nach Launch',
    'Vertrag SEO-Betreuung, 6 Monate, 550 € monatlich',
    'Agenturvertrag Retainer Design, 20 Stunden monatlich',
    'Vertrag Datenschutz-Audit, einmalig 3.600 €',
    'Kooperationsvertrag White-Label, 24 Monate, Umsatzbeteiligung',
    'Vertrag Schulung und Enablement, 2 Tage, 3.200 €',
    'Rahmenvertrag IT-Support, 50 Stunden Kontingent, 12 Monate',
    'Vertrag Social Ads Betreuung, 6 Monate, 1.100 € monatlich',
    'Vertrag Prototyping MVP, 10 Wochen, 22.000 €',
    'Vertrag Übergabe und Dokumentation, Pauschal 1.450 €',
  ],
}
