'use client'

import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import TagroLogo from '@/components/TagroLogo'
import {
  ArrowLeft,
  Brain,
  CalendarBlank,
  CheckCircle,
  Clock,
  FileText,
  Flag,
  GitBranch,
  Link as LinkIcon,
  Pause,
  Plugs,
  ShieldCheck,
  Sparkle,
  Tag,
  Trash,
  UserCircle,
  UsersThree,
  WarningCircle,
} from '@phosphor-icons/react'

type TaskDetail = {
  id: string
  title: string
  description?: string | null
  client_description?: string | null
  dev_description?: string | null
  status?: string | null
  priority?: string | null
  project_id?: string | null
  assigned_to?: string | null
  created_by?: string | null
  approved_by?: string | null
  owner?: string | null
  developer_name?: string | null
  source?: string | null
  origin?: string | null
  task_type?: string | null
  group_key?: string | null
  audience?: string | null
  client_visible?: boolean | null
  client_status?: string | null
  dev_status?: string | null
  latest_client_update?: string | null
  latest_dev_update?: string | null
  customer_update?: string | null
  dev_notes?: string | null
  due_date?: string | null
  progress?: number | null
  label?: string | null
  tags?: string[] | null
  attachments_json?: unknown
  tagro_result_json?: any
  created_at?: string | null
  updated_at?: string | null
}

type Project = {
  id: string
  title: string
  description?: string | null
  status?: string | null
  color?: string | null
  client_id?: string | null
}

type Profile = {
  id: string
  email?: string | null
  full_name?: string | null
  first_name?: string | null
  avatar_url?: string | null
  avatar_color?: string | null
  role?: string | null
}

type ActivityItem = {
  id: string
  title?: string | null
  message?: string | null
  event_type?: string | null
  actor_role?: string | null
  created_at?: string | null
}

type MessageItem = {
  id: string
  message?: string | null
  created_at?: string | null
  is_ai?: boolean | null
}

const DONE_STATES = new Set(['done', 'completed', 'delivered', 'erledigt'])
const ACTIVE_STATES = new Set(['doing', 'active', 'in_progress', 'development', 'in_development'])
const DECISION_STATES = new Set(['blocked', 'waiting', 'needs_decision', 'client_decision', 'waiting_for_client', 'waiting_for_assignment'])
const REVIEW_STATES = new Set(['review', 'ready_for_review', 'in_review', 'festag_review', 'suggested', 'zur_pruefung', 'verified', 'approved', 'festag_checked'])

function normalizeStatus(status?: string | null) {
  const value = (status || 'todo').toLowerCase()
  if (DONE_STATES.has(value)) return 'done'
  if (REVIEW_STATES.has(value)) return 'review'
  if (DECISION_STATES.has(value)) return 'decision'
  if (ACTIVE_STATES.has(value)) return 'active'
  return 'open'
}

function taskState(task?: TaskDetail | null) {
  if (!task) return 'submitted'
  return task.client_status || task.status || task.dev_status || 'submitted'
}

function statusLabel(status?: string | null) {
  const normalized = normalizeStatus(status)
  if (normalized === 'done') return 'Erledigt'
  if (normalized === 'review') return 'In Prüfung'
  if (normalized === 'decision') return 'Warten'
  if (normalized === 'active') return 'In Arbeit'
  return 'Offen'
}

function priorityLabel(priority?: string | null) {
  if (priority === 'critical') return 'Kritisch'
  if (priority === 'high') return 'Hoch'
  if (priority === 'medium') return 'Mittel'
  if (priority === 'low') return 'Niedrig'
  return 'Keine Priorität'
}

function sourceLabel(source?: string | null, origin?: string | null) {
  const value = source || origin
  if (value === 'client_manual') return 'Created manually'
  if (value === 'client_tagro') return 'Suggested by Tagro'
  if (value === 'status_report' || value === 'ai_report') return 'Created from status report'
  if (value === 'decision') return 'Created from decision'
  if (value === 'briefing') return 'Created from briefing'
  if (value === 'github_activity') return 'Imported from GitHub'
  if (value === 'admin' || value === 'developer') return 'Created by project team'
  if (value === 'tagro_internal') return 'Generated by Tagro'
  if (value === 'system') return 'Created by system'
  return 'Created manually'
}

function sourceActor(source?: string | null) {
  if (source === 'client_tagro' || source === 'tagro_internal') return 'Tagro'
  if (source === 'github_activity') return 'GitHub Integration'
  if (source === 'briefing') return 'Tagro Briefing'
  if (source === 'status_report' || source === 'ai_report') return 'Status Report'
  if (source === 'client_manual') return 'Client Portal'
  if (source === 'system') return 'System'
  return 'Project Team'
}

function progressFor(task: TaskDetail) {
  if (typeof task.progress === 'number') return task.progress
  const normalized = normalizeStatus(taskState(task))
  if (normalized === 'done') return 100
  if (normalized === 'review') return 82
  if (normalized === 'decision') return 40
  if (normalized === 'active') return 55
  return 0
}

function dateLabel(value?: string | null) {
  if (!value) return 'Not set'
  try {
    return new Intl.DateTimeFormat('de-DE', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value))
  } catch {
    return 'Not set'
  }
}

function relativeDate(value?: string | null) {
  if (!value) return 'unknown'
  const diff = Date.now() - new Date(value).getTime()
  const minutes = Math.max(1, Math.round(diff / 60000))
  if (minutes < 60) return `vor ${minutes} Min.`
  const hours = Math.round(minutes / 60)
  if (hours < 24) return `vor ${hours} Std.`
  const days = Math.round(hours / 24)
  return `vor ${days} Tagen`
}

function displayName(profile?: Profile | null, fallback = 'Unassigned') {
  if (!profile) return fallback
  return profile.full_name || profile.first_name || profile.email || fallback
}

function initials(name: string) {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part.charAt(0).toUpperCase())
    .join('') || 'U'
}

function hasDecisionNeed(task: TaskDetail) {
  const status = taskState(task).toLowerCase()
  const text = `${task.title} ${task.latest_client_update ?? ''} ${task.client_description ?? ''}`.toLowerCase()
  return DECISION_STATES.has(status) || /entscheidung|freigabe|approval|approve|client/.test(text)
}

function hasRisk(task: TaskDetail) {
  const status = taskState(task).toLowerCase()
  const text = `${task.title} ${task.latest_client_update ?? ''} ${task.dev_notes ?? ''} ${task.dev_description ?? ''}`.toLowerCase()
  return status === 'blocked' || /blocker|risiko|risk|delay|verzöger|wartet/.test(text)
}

function safeText(value?: string | null) {
  return value && value.trim() ? value.trim() : null
}

function buildFallbackExplanation(task: TaskDetail, project?: Project | null) {
  const status = statusLabel(taskState(task)).toLowerCase()
  const projectPart = project?.title ? ` im Projekt "${project.title}"` : ''
  const expected = safeText(task.client_description) || safeText(task.description) || safeText(task.latest_client_update) || 'Der genaue Arbeitsumfang wird aus dem Projektkontext weiter konkretisiert.'
  const risk = hasRisk(task) ? ' Es gibt ein mögliches Risiko oder einen Blocker, der aktiv beobachtet werden sollte.' : ' Aktuell ist kein klarer Blocker erkennbar.'
  const decision = hasDecisionNeed(task) ? ' Eine Entscheidung oder Rueckmeldung eines Stakeholders kann erforderlich sein.' : ' Im Moment wirkt keine direkte Entscheidung erforderlich.'
  return `Diese Aufgabe${projectPart} beschreibt einen konkreten Arbeitsschritt mit dem Status ${status}. ${expected} Sie ist wichtig, weil sie Einfluss auf Projektfortschritt, Verantwortung und die naechsten kommunizierbaren Schritte hat.${risk}${decision}`
}

function avatarFor(profile: Profile | null, fallbackName: string) {
  const name = displayName(profile, fallbackName)
  if (profile?.avatar_url) {
    return <img src={profile.avatar_url} alt="" />
  }
  return <span>{initials(name)}</span>
}

type TaskWorkspaceDetailProps = {
  taskId: string
  projectId?: string
}

export default function TaskWorkspaceDetail({ taskId, projectId }: TaskWorkspaceDetailProps) {
  const router = useRouter()
  const supabase = createClient()
  const [task, setTask] = useState<TaskDetail | null>(null)
  const [project, setProject] = useState<Project | null>(null)
  const [profiles, setProfiles] = useState<Record<string, Profile>>({})
  const [activity, setActivity] = useState<ActivityItem[]>([])
  const [messages, setMessages] = useState<MessageItem[]>([])
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [tagroExplanation, setTagroExplanation] = useState('')
  const [tagroLoading, setTagroLoading] = useState(false)

  useEffect(() => {
    let cancelled = false

    async function loadTaskDetail() {
      setLoading(true)
      const { data: taskData } = await (supabase as any)
        .from('tasks')
        .select('*')
        .eq('id', taskId)
        .maybeSingle()

      if (!taskData) {
        if (!cancelled) {
          setTask(null)
          setLoading(false)
        }
        return
      }

      const loadedTask = taskData as TaskDetail
      const pid = projectId || loadedTask.project_id || null

      const profileIds = [loadedTask.assigned_to, loadedTask.created_by, loadedTask.approved_by]
        .filter(Boolean) as string[]

      const [projectResult, activityResult, messagesResult, profilesResult] = await Promise.all([
        pid ? (supabase as any).from('projects').select('*').eq('id', pid).maybeSingle() : Promise.resolve({ data: null }),
        pid ? (supabase as any).from('activity_feed').select('id,title,message,event_type,actor_role,created_at').eq('project_id', pid).order('created_at', { ascending: false }).limit(8).then((result: any) => result, () => ({ data: [] })) : Promise.resolve({ data: [] }),
        pid ? (supabase as any).from('messages').select('id,message,created_at,is_ai').eq('project_id', pid).order('created_at', { ascending: false }).limit(6).then((result: any) => result, () => ({ data: [] })) : Promise.resolve({ data: [] }),
        profileIds.length ? (supabase as any).from('profiles').select('id,email,full_name,first_name,avatar_url,avatar_color,role').in('id', profileIds).then((result: any) => result, () => ({ data: [] })) : Promise.resolve({ data: [] }),
      ])

      if (cancelled) return

      const profileMap = new Map<string, Profile>()
      ;((profilesResult.data as Profile[]) ?? []).forEach((profile) => profileMap.set(profile.id, profile))

      setTask(loadedTask)
      setProject((projectResult.data as Project | null) ?? null)
      setActivity((activityResult.data as ActivityItem[]) ?? [])
      setMessages((messagesResult.data as MessageItem[]) ?? [])
      setProfiles(Object.fromEntries(profileMap))
      setLoading(false)
    }

    loadTaskDetail()

    const channel = supabase
      .channel(`task-detail-${taskId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'tasks', filter: `id=eq.${taskId}` }, () => {
        loadTaskDetail()
      })
      .subscribe()

    return () => {
      cancelled = true
      supabase.removeChannel(channel)
    }
  }, [taskId, projectId])

  useEffect(() => {
    if (!task) return
    let cancelled = false
    const fallback = buildFallbackExplanation(task, project)
    setTagroExplanation(fallback)
    setTagroLoading(true)

    fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system: 'Du bist Tagro, die Verstaendlichkeitsschicht von Festag. Erklaere Tasks in ruhiger, einfacher, executive-freundlicher Sprache. Keine internen Annahmen, keine Fachbegriffe ohne kurze Einordnung. Antworte auf Deutsch in 3-5 kurzen Saetzen.',
        messages: [{
          role: 'user',
          content: `Projekt: ${project?.title ?? 'Unbekannt'}\nTask: ${task.title}\nStatus: ${statusLabel(taskState(task))}\nPrioritaet: ${priorityLabel(task.priority)}\nBeschreibung: ${task.client_description || task.description || task.dev_description || 'Keine Beschreibung'}\nLetztes Update: ${task.latest_client_update || task.customer_update || task.latest_dev_update || 'Kein Update'}\n\nErklaere: worum es geht, warum es fuer das Projekt wichtig ist, was noch fehlt, ob Risiko/Blocker/Entscheidung sichtbar ist und was der naechste sinnvolle Schritt ist.`,
        }],
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        if (!cancelled) setTagroExplanation(data.content?.[0]?.text || fallback)
      })
      .catch(() => {
        if (!cancelled) setTagroExplanation(fallback)
      })
      .finally(() => {
        if (!cancelled) setTagroLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [task?.id, project?.id])

  const assignedProfile = task?.assigned_to ? profiles[task.assigned_to] : null
  const createdProfile = task?.created_by ? profiles[task.created_by] : null
  const approvedProfile = task?.approved_by ? profiles[task.approved_by] : null
  const ownerName = task?.developer_name || task?.owner || displayName(assignedProfile, task?.assigned_to ? 'Assigned teammate' : 'Unassigned')
  const createdBy = displayName(createdProfile, sourceActor(task?.source))
  const requestedBy = task?.source === 'client_manual' || task?.source === 'client_tagro' ? 'Client' : task?.source === 'decision' ? 'Project Owner' : task?.source === 'github_activity' ? 'GitHub Integration' : 'Project Team'
  const normalized = normalizeStatus(taskState(task))
  const decisionNeeded = task ? hasDecisionNeed(task) : false
  const riskVisible = task ? hasRisk(task) : false
  const manageable = task?.source === 'client_manual' || task?.source === 'client_tagro'

  const timeline = useMemo(() => {
    if (!task) return []
    const items = [
      {
        id: 'created',
        label: `${sourceActor(task.source)} created this task`,
        meta: dateLabel(task.created_at),
        kind: task.source === 'client_tagro' || task.source === 'tagro_internal' ? 'tagro' : 'source',
      },
      task.assigned_to || task.developer_name || task.owner ? {
        id: 'assigned',
        label: `${ownerName} owns execution`,
        meta: task.updated_at ? relativeDate(task.updated_at) : 'current',
        kind: 'owner',
      } : null,
      task.latest_client_update ? {
        id: 'client-update',
        label: task.latest_client_update,
        meta: 'Client-safe update',
        kind: 'update',
      } : null,
      ...activity.slice(0, 4).map((item) => ({
        id: item.id,
        label: item.title || item.message || item.event_type || 'Project activity',
        meta: relativeDate(item.created_at),
        kind: 'activity',
      })),
    ].filter(Boolean)
    return items as { id: string; label: string; meta: string; kind: string }[]
  }, [task, activity, ownerName])

  function openCopilot(prompt: string) {
    window.dispatchEvent(new CustomEvent('open-copilot'))
    window.dispatchEvent(new CustomEvent('tagro-compose', { detail: { prompt } }))
  }

  async function pauseTask() {
    if (!task || busy || !manageable) return
    setBusy(true)
    try {
      await (supabase as any).from('tasks').update({
        status: 'waiting',
        client_status: 'waiting',
        updated_at: new Date().toISOString(),
      }).eq('id', task.id)
    } finally {
      setBusy(false)
    }
  }

  async function deleteTask() {
    if (!task || busy || !manageable) return
    const confirmed = window.confirm('Diese eigene Aufgabe wirklich löschen?')
    if (!confirmed) return
    setBusy(true)
    try {
      await (supabase as any).from('tasks').delete().eq('id', task.id)
      router.push(project?.id ? `/project/${project.id}?tab=tasks` : '/tasks')
    } finally {
      setBusy(false)
    }
  }

  if (loading) {
    return (
      <div className="task-detail-shell">
        <style>{detailStyles}</style>
        <div className="task-detail-loading">Lade Task-Detail...</div>
      </div>
    )
  }

  if (!task) {
    return (
      <div className="task-detail-shell">
        <style>{detailStyles}</style>
        <div className="task-detail-empty">
          <h1>Task nicht gefunden</h1>
          <p>Diese Aufgabe existiert nicht mehr oder ist fuer deinen Workspace nicht sichtbar.</p>
          <Link href="/tasks">Zurueck zu Tasks</Link>
        </div>
      </div>
    )
  }

  const description = safeText(task.client_description) || safeText(task.description) || safeText(task.dev_description) || 'Noch keine ausfuehrliche Beschreibung hinterlegt.'
  const latestUpdate = safeText(task.latest_client_update) || safeText(task.customer_update) || safeText(task.latest_dev_update) || safeText(task.dev_notes) || 'Noch kein belastbares Update vorhanden.'
  const tags = [...(task.tags ?? []), task.label].filter(Boolean) as string[]
  const source = sourceLabel(task.source, task.origin)

  return (
    <div className="task-detail-shell">
      <style>{detailStyles}</style>

      <div className="task-detail-topbar">
        <button type="button" onClick={() => router.back()} className="task-back">
          <ArrowLeft size={15} />
          Zurueck
        </button>
        <div className="task-breadcrumb">
          <Link href="/projects">Projects</Link>
          <span>/</span>
          {project ? <Link href={`/project/${project.id}?tab=tasks`}>{project.title}</Link> : <Link href="/tasks">Tasks</Link>}
          <span>/</span>
          <strong>{task.title}</strong>
        </div>
      </div>

      <div className="task-detail-grid-page">
        <main className="task-detail-main">
          <section className="task-hero">
            <div className={`status-pill ${normalized}`}>
              <span />
              {statusLabel(taskState(task))}
            </div>
            <h1>{task.title}</h1>
            <p className="task-attribution">
              Requested by {requestedBy} · Created by {createdBy} · Assigned to {ownerName}
            </p>
          </section>

          <section className="tagro-explanation-card">
            <div className="section-head">
              <div className="tagro-title">
                <TagroLogo size={28} thinking={tagroLoading} />
                <div>
                  <p>Explained by Tagro</p>
                  <span>{tagroLoading ? 'Tagro schreibt eine klare Einordnung...' : `Updated ${relativeDate(task.updated_at || task.created_at)}`}</span>
                </div>
              </div>
              <Sparkle size={17} weight="fill" />
            </div>
            <p>{tagroExplanation}</p>
          </section>

          <section className="task-section">
            <div className="section-head">
              <h2>Current status</h2>
              <span>{progressFor(task)}% progress</span>
            </div>
            <div className="status-grid">
              <article>
                <Clock size={17} />
                <strong>{statusLabel(taskState(task))}</strong>
                <span>{latestUpdate}</span>
              </article>
              <article>
                <WarningCircle size={17} />
                <strong>{riskVisible ? 'Risk visible' : 'No clear blocker'}</strong>
                <span>{riskVisible ? 'Tagro should keep this in the next status report.' : 'No explicit risk signal in the current task data.'}</span>
              </article>
              <article>
                <ShieldCheck size={17} />
                <strong>{decisionNeeded ? 'Decision required' : 'No decision needed'}</strong>
                <span>{decisionNeeded ? 'A stakeholder response may be needed before progress continues.' : 'The next step can continue without visible leadership approval.'}</span>
              </article>
            </div>
          </section>

          <section className="task-section">
            <h2>Description</h2>
            <p>{description}</p>
          </section>

          <section className="task-section">
            <h2>Latest update</h2>
            <p>{latestUpdate}</p>
          </section>

          <section className="task-section">
            <div className="section-head">
              <h2>Tagro insights</h2>
              <span>Reporting layer</span>
            </div>
            <div className="insight-list">
              <div><strong>What changed?</strong><span>{latestUpdate}</span></div>
              <div><strong>Risk or blocker</strong><span>{riskVisible ? 'Potential blocker/risk detected from task status or wording.' : 'No explicit blocker detected.'}</span></div>
              <div><strong>Next recommended action</strong><span>{decisionNeeded ? 'Ask the responsible stakeholder for a decision or approval.' : 'Let the owner continue and request a short progress update after the next change.'}</span></div>
              <div><strong>Who needs to respond?</strong><span>{decisionNeeded ? requestedBy : ownerName}</span></div>
              <div><strong>Status report?</strong><span>{riskVisible || decisionNeeded ? 'Include this in the next status report.' : 'Mention only if the project owner wants detailed task context.'}</span></div>
            </div>
          </section>

          <section className="task-section">
            <div className="section-head">
              <h2>Activity timeline</h2>
              <span>{timeline.length} events</span>
            </div>
            <div className="timeline">
              {timeline.map((item) => (
                <div key={item.id} className="timeline-item">
                  <span className={`timeline-dot ${item.kind}`} />
                  <div>
                    <strong>{item.label}</strong>
                    <p>{item.meta}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="task-section">
            <div className="section-head">
              <h2>Comments / discussion</h2>
              <span>Project context</span>
            </div>
            {messages.length ? (
              <div className="discussion-list">
                {messages.slice().reverse().map((message) => (
                  <article key={message.id}>
                    <strong>{message.is_ai ? 'Tagro' : 'Workspace message'}</strong>
                    <p>{message.message || 'No message body'}</p>
                    <span>{relativeDate(message.created_at)}</span>
                  </article>
                ))}
              </div>
            ) : (
              <p>No task-specific discussion yet. Project messages and Tagro updates will appear here as the workspace collects more signals.</p>
            )}
          </section>
        </main>

        <aside className="task-properties">
          <section className="property-card">
            <div className="property-head">
              <h2>Properties</h2>
              <span>{source}</span>
            </div>
            <PropertyRow icon={<CheckCircle size={16} />} label="Status" value={statusLabel(taskState(task))} />
            <PropertyRow icon={<Flag size={16} />} label="Priority" value={priorityLabel(task.priority)} />
            <PropertyRow icon={<UserCircle size={16} />} label="Created by" value={createdBy} />
            <PropertyRow icon={<UsersThree size={16} />} label="Requested by" value={requestedBy} />
            <PropertyRow
              icon={<span className="mini-avatar">{avatarFor(assignedProfile, ownerName)}</span>}
              label="Assigned to"
              value={`${ownerName}${assignedProfile?.role ? ` · ${assignedProfile.role}` : ''}`}
            />
            <PropertyRow icon={<Brain size={16} />} label="Explained by" value={`Tagro · ${relativeDate(task.updated_at || task.created_at)}`} />
            <PropertyRow icon={<Plugs size={16} />} label="Source" value={source} />
            <PropertyRow icon={<CalendarBlank size={16} />} label="Due date" value={dateLabel(task.due_date)} />
            <PropertyRow icon={<FileText size={16} />} label="Project" value={project?.title || 'No project'} />
            <PropertyRow icon={<ShieldCheck size={16} />} label="Visibility" value={task.client_visible === false ? 'Internal team only' : 'Client visible'} />
            <PropertyRow icon={<WarningCircle size={16} />} label="Risk level" value={riskVisible ? 'Needs attention' : 'Low'} />
            <PropertyRow icon={<Clock size={16} />} label="Decision required" value={decisionNeeded ? 'Yes' : 'No'} />
            <PropertyRow icon={<GitBranch size={16} />} label="Last updated" value={dateLabel(task.updated_at || task.created_at)} />
            {approvedProfile ? <PropertyRow icon={<CheckCircle size={16} />} label="Approved by" value={displayName(approvedProfile)} /> : null}
          </section>

          <section className="property-card">
            <div className="property-head">
              <h2>Stakeholder clarity</h2>
              <span>Accountability</span>
            </div>
            <p className="property-copy">This view separates who requested the work, who created the task, who owns execution, and what Tagro added for understanding.</p>
            <div className="origin-stack">
              <OriginBadge label={task.source === 'client_tagro' ? 'Suggested by Tagro' : source} kind={task.source || 'manual'} />
              <OriginBadge label={`Assigned to ${ownerName}`} kind="owner" />
              <OriginBadge label={`Explained by Tagro`} kind="tagro" />
            </div>
          </section>

          <section className="property-card">
            <div className="property-head">
              <h2>Files & links</h2>
              <span>Signals</span>
            </div>
            <PropertyRow icon={<LinkIcon size={16} />} label="Connected source" value={task.origin || task.source || 'Workspace'} />
            <PropertyRow icon={<Tag size={16} />} label="Tags" value={tags.length ? tags.join(', ') : 'No tags'} />
          </section>

          <section className="property-card actions">
            <button type="button" onClick={() => openCopilot(`Erklaere diese Aufgabe fuer einen CEO oder Client und sage, was als naechstes entschieden oder kommuniziert werden sollte: "${task.title}"`)}>
              Ask Tagro
            </button>
            <button type="button" onClick={() => openCopilot(`Soll diese Aufgabe im naechsten Statusbericht auftauchen? Pruefe Risiko, Blocker, Entscheidung und Stakeholder-Kommunikation: "${task.title}"`)}>
              Check report relevance
            </button>
            {manageable ? <button type="button" onClick={pauseTask} disabled={busy}><Pause size={14} /> Aussetzen</button> : null}
            {manageable ? <button type="button" className="danger" onClick={deleteTask} disabled={busy}><Trash size={14} /> Loeschen</button> : null}
          </section>
        </aside>
      </div>
    </div>
  )
}

function PropertyRow({ icon, label, value }: { icon: ReactNode; label: string; value: string }) {
  return (
    <div className="property-row">
      <span className="property-icon">{icon}</span>
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  )
}

function OriginBadge({ label, kind }: { label: string; kind: string }) {
  return (
    <div className={`origin-badge ${kind}`}>
      <span />
      {label}
    </div>
  )
}

const detailStyles = `
  .task-detail-shell {
    width:100%;
    min-height:100%;
    color:var(--text);
    padding:20px 24px 72px;
  }
  .task-detail-topbar {
    display:flex;
    align-items:center;
    justify-content:space-between;
    gap:16px;
    margin-bottom:18px;
    min-height:34px;
  }
  .task-back {
    height:32px;
    display:inline-flex;
    align-items:center;
    gap:8px;
    padding:0 12px;
    border-radius:10px;
    border:1px solid var(--border);
    background:var(--surface);
    color:var(--text-secondary);
    font:inherit;
    font-size:12px;
    font-weight:700;
    cursor:pointer;
  }
  .task-back:hover { background:var(--surface-2); color:var(--text); }
  .task-breadcrumb {
    display:flex;
    align-items:center;
    justify-content:flex-end;
    min-width:0;
    gap:8px;
    color:var(--text-muted);
    font-size:12px;
  }
  .task-breadcrumb a {
    color:var(--text-muted);
    text-decoration:none;
  }
  .task-breadcrumb strong {
    max-width:260px;
    overflow:hidden;
    text-overflow:ellipsis;
    white-space:nowrap;
    color:var(--text-secondary);
  }
  .task-detail-grid-page {
    display:grid;
    grid-template-columns:minmax(0,1fr) minmax(300px,360px);
    gap:24px;
    align-items:start;
  }
  .task-detail-main {
    min-width:0;
    display:flex;
    flex-direction:column;
    gap:16px;
  }
  .task-hero {
    padding:32px 34px 28px;
    border:1px solid var(--border);
    border-radius:18px;
    background:var(--surface);
  }
  .status-pill {
    height:28px;
    display:inline-flex;
    align-items:center;
    gap:8px;
    padding:0 11px;
    border-radius:999px;
    color:var(--text-secondary);
    border:1px solid var(--border);
    font-size:11.5px;
    font-weight:760;
    letter-spacing:.03em;
    margin-bottom:18px;
  }
  .status-pill span {
    width:8px;
    height:8px;
    border-radius:50%;
    background:var(--text-muted);
  }
  .status-pill.active span { background:var(--amber); }
  .status-pill.decision span { background:var(--amber); box-shadow:0 0 0 4px color-mix(in srgb, var(--amber) 14%, transparent); }
  .status-pill.review span { background:#6366f1; }
  .status-pill.done span { background:var(--green); }
  .task-hero h1 {
    max-width:900px;
    margin:0;
    color:var(--text);
    font-size:clamp(30px, 4vw, 54px);
    line-height:1.02;
    letter-spacing:-.04em;
    font-weight:760;
  }
  .task-attribution {
    margin:18px 0 0;
    color:var(--text-secondary);
    font-size:13px;
    line-height:1.55;
  }
  .tagro-explanation-card,
  .task-section,
  .property-card {
    border:1px solid var(--border);
    border-radius:16px;
    background:var(--surface);
  }
  .tagro-explanation-card {
    padding:20px 22px;
    background:linear-gradient(135deg, color-mix(in srgb, var(--surface) 88%, var(--green-bg)), var(--surface));
  }
  .section-head {
    display:flex;
    align-items:flex-start;
    justify-content:space-between;
    gap:14px;
    margin-bottom:12px;
  }
  .section-head h2,
  .property-head h2,
  .task-section h2 {
    margin:0;
    color:var(--text);
    font-size:13px;
    font-weight:760;
    letter-spacing:.02em;
  }
  .section-head span,
  .property-head span {
    color:var(--text-muted);
    font-size:11px;
    font-weight:700;
    letter-spacing:.06em;
    text-transform:uppercase;
  }
  .tagro-title {
    display:flex;
    align-items:center;
    gap:11px;
    min-width:0;
  }
  .tagro-title p {
    margin:0;
    color:var(--text);
    font-size:13px;
    font-weight:760;
  }
  .tagro-title span {
    display:block;
    margin-top:2px;
    color:var(--text-muted);
    font-size:11.5px;
  }
  .tagro-explanation-card > p,
  .task-section > p,
  .property-copy {
    margin:0;
    color:var(--text-secondary);
    font-size:14px;
    line-height:1.72;
  }
  .task-section {
    padding:20px 22px;
  }
  .status-grid {
    display:grid;
    grid-template-columns:repeat(3,minmax(0,1fr));
    gap:10px;
  }
  .status-grid article {
    min-height:120px;
    padding:14px;
    border-radius:14px;
    border:1px solid color-mix(in srgb, var(--border) 72%, transparent);
    background:color-mix(in srgb, var(--surface-2) 44%, transparent);
    display:flex;
    flex-direction:column;
    gap:9px;
  }
  .status-grid svg { color:var(--text-muted); }
  .status-grid strong {
    color:var(--text);
    font-size:13px;
    font-weight:760;
  }
  .status-grid span {
    color:var(--text-secondary);
    font-size:12.5px;
    line-height:1.55;
  }
  .insight-list {
    display:grid;
    gap:9px;
  }
  .insight-list div {
    display:grid;
    grid-template-columns:180px minmax(0,1fr);
    gap:14px;
    padding:10px 0;
    border-top:1px solid color-mix(in srgb, var(--border) 64%, transparent);
  }
  .insight-list div:first-child { border-top:0; padding-top:0; }
  .insight-list strong {
    color:var(--text);
    font-size:12.5px;
    font-weight:760;
  }
  .insight-list span,
  .timeline-item p,
  .discussion-list span {
    color:var(--text-muted);
    font-size:12px;
    line-height:1.55;
  }
  .timeline {
    display:grid;
    gap:12px;
  }
  .timeline-item {
    display:grid;
    grid-template-columns:20px minmax(0,1fr);
    gap:10px;
  }
  .timeline-dot {
    width:10px;
    height:10px;
    border-radius:50%;
    margin:4px 0 0 5px;
    background:var(--text-muted);
  }
  .timeline-dot.tagro { background:var(--green); }
  .timeline-dot.owner { background:#6366f1; }
  .timeline-dot.update { background:var(--amber); }
  .timeline-item strong {
    color:var(--text-secondary);
    font-size:13px;
    font-weight:650;
    line-height:1.45;
  }
  .timeline-item p {
    margin:3px 0 0;
  }
  .discussion-list {
    display:grid;
    gap:10px;
  }
  .discussion-list article {
    padding:12px;
    border:1px solid color-mix(in srgb, var(--border) 72%, transparent);
    border-radius:12px;
    background:color-mix(in srgb, var(--surface-2) 34%, transparent);
  }
  .discussion-list strong {
    display:block;
    color:var(--text);
    font-size:12.5px;
    margin-bottom:4px;
  }
  .discussion-list p {
    margin:0 0 8px;
    color:var(--text-secondary);
    font-size:12.5px;
    line-height:1.55;
  }
  .task-properties {
    position:sticky;
    top:18px;
    display:flex;
    flex-direction:column;
    gap:12px;
    min-width:0;
  }
  .property-card {
    padding:16px;
  }
  .property-head {
    display:flex;
    align-items:flex-start;
    justify-content:space-between;
    gap:10px;
    margin-bottom:12px;
  }
  .property-row {
    min-height:34px;
    display:grid;
    grid-template-columns:20px 104px minmax(0,1fr);
    align-items:center;
    gap:8px;
    color:var(--text-muted);
    font-size:12px;
  }
  .property-row strong {
    color:var(--text-secondary);
    font-size:12.5px;
    font-weight:650;
    overflow:hidden;
    text-overflow:ellipsis;
    white-space:nowrap;
    text-align:right;
  }
  .property-icon {
    color:var(--text-muted);
    display:flex;
    align-items:center;
    justify-content:center;
  }
  .mini-avatar,
  .mini-avatar img,
  .mini-avatar span {
    width:20px;
    height:20px;
    border-radius:50%;
    display:flex;
    align-items:center;
    justify-content:center;
    object-fit:cover;
  }
  .mini-avatar span {
    background:var(--surface-2);
    border:1px solid var(--border);
    color:var(--text-secondary);
    font-size:9px;
    font-weight:800;
  }
  .origin-stack {
    display:grid;
    gap:8px;
    margin-top:12px;
  }
  .origin-badge {
    min-height:30px;
    display:flex;
    align-items:center;
    gap:8px;
    color:var(--text-secondary);
    font-size:12px;
    font-weight:650;
  }
  .origin-badge span {
    width:18px;
    height:18px;
    border-radius:6px;
    background:var(--surface-2);
    border:1px solid var(--border);
  }
  .origin-badge.client_tagro span,
  .origin-badge.tagro span,
  .origin-badge.tagro_internal span { background:var(--green-bg); border-color:color-mix(in srgb, var(--green) 28%, var(--border)); }
  .origin-badge.github_activity span { background:#111827; border-color:#111827; }
  .origin-badge.owner span { background:#eef2ff; border-color:#c7d2fe; }
  .property-card.actions {
    display:grid;
    gap:8px;
  }
  .property-card.actions button {
    min-height:38px;
    display:flex;
    align-items:center;
    justify-content:center;
    gap:8px;
    border:1px solid var(--border);
    border-radius:11px;
    background:var(--surface-2);
    color:var(--text);
    font:inherit;
    font-size:12.5px;
    font-weight:760;
    cursor:pointer;
  }
  .property-card.actions button:hover { border-color:var(--border-strong); }
  .property-card.actions button.danger {
    color:var(--red);
    background:transparent;
  }
  .property-card.actions button:disabled {
    opacity:.5;
    cursor:not-allowed;
  }
  .task-detail-loading,
  .task-detail-empty {
    max-width:520px;
    margin:120px auto 0;
    padding:28px;
    border:1px solid var(--border);
    border-radius:16px;
    background:var(--surface);
    color:var(--text-secondary);
    text-align:center;
  }
  .task-detail-empty h1 {
    margin:0 0 8px;
    color:var(--text);
    font-size:24px;
  }
  .task-detail-empty a {
    display:inline-flex;
    margin-top:16px;
    color:var(--text);
    font-weight:700;
  }
  @media(max-width:1100px) {
    .task-detail-grid-page {
      grid-template-columns:minmax(0,1fr);
    }
    .task-properties {
      position:static;
    }
  }
  @media(max-width:760px) {
    .task-detail-shell {
      padding:14px 12px calc(96px + var(--safe-bottom));
    }
    .task-detail-topbar {
      align-items:flex-start;
      flex-direction:column;
    }
    .task-breadcrumb {
      justify-content:flex-start;
      width:100%;
    }
    .task-hero,
    .tagro-explanation-card,
    .task-section,
    .property-card {
      border-radius:14px;
    }
    .task-hero {
      padding:24px 18px;
    }
    .status-grid {
      grid-template-columns:1fr;
    }
    .insight-list div {
      grid-template-columns:1fr;
      gap:5px;
    }
    .property-row {
      grid-template-columns:20px 92px minmax(0,1fr);
    }
  }
`
