// Festag Add-on Marketplace
// Jeder Eintrag ist ein "Befehl" fuer das Entwicklerteam — beschreibt
// klar was geliefert wird und enthaelt eine konkrete Dev-Instruction.

export type Addon = {
  id: string
  name: string
  description: string
  price: number              // EUR
  category: AddonCategory
  icon: string
  features: string[]
  devInstructions: string    // klare Anweisung fuer den Entwickler
  estimatedHours: number
  tags: string[]
  popular?: boolean
}

export type AddonCategory =
  | 'Design'
  | 'Frontend'
  | 'Backend'
  | 'AI'
  | 'Marketing'
  | 'E-Commerce'
  | 'Analytics'
  | 'Mobile'
  | 'DevOps'
  | 'Security'

export const CATEGORIES: { key: AddonCategory; label: string; emoji: string }[] = [
  { key: 'Design',     label: 'Design',          emoji: '🎨' },
  { key: 'Frontend',   label: 'Frontend',        emoji: '🖥️' },
  { key: 'Backend',    label: 'Backend',         emoji: '🛠️' },
  { key: 'AI',         label: 'AI & Automation', emoji: '✦' },
  { key: 'Marketing',  label: 'Marketing & SEO', emoji: '📣' },
  { key: 'E-Commerce', label: 'E-Commerce',      emoji: '🛒' },
  { key: 'Analytics',  label: 'Analytics',       emoji: '📊' },
  { key: 'Mobile',     label: 'Mobile',          emoji: '📱' },
  { key: 'DevOps',     label: 'DevOps',          emoji: '⚙️' },
  { key: 'Security',   label: 'Security',        emoji: '🔒' },
]

export const CATALOG: Addon[] = [
  // ─────────────────────────── DESIGN ───────────────────────────
  { id: 'branding-pro', name: 'Branding Paket Pro', description: 'Logo, Farbpalette, Typografie, Brand Guidelines', price: 1290, category: 'Design', icon: 'brand',
    features: ['Logo (Vektor + Varianten)', 'Farbpalette mit HEX/RGB', 'Typografie-System', 'Brand Guidelines PDF', 'Logo-Anwendungsbeispiele'],
    devInstructions: 'Erstelle eine vollstaendige Brand Identity: Logo in 3 Varianten (Wort-, Bild-, Kombi-Marke), Farbpalette mit Primary/Secondary/Accent inkl. Light/Dark, 2 Schriftarten (Display + Body), und ein 12-seitiges Guidelines-PDF mit Anwendungsbeispielen.',
    estimatedHours: 32, tags: ['logo', 'identity', 'guidelines'], popular: true },
  { id: 'design-system', name: 'Design System mit Tokens', description: 'Komponenten-Bibliothek, Design-Tokens, Storybook', price: 1890, category: 'Design', icon: 'system',
    features: ['Design-Tokens (Farben, Spacing, Radii)', '30+ Komponenten in Figma', 'Storybook-Setup', 'Token-Export zu Code', 'Light & Dark Theme'],
    devInstructions: 'Baue ein produktives Design-System mit 30+ wiederverwendbaren Komponenten in Figma, exportiere Design-Tokens zu CSS-Variablen oder TS-Konstanten, richte Storybook ein und dokumentiere jede Komponente.',
    estimatedHours: 60, tags: ['figma', 'tokens', 'storybook'] },
  { id: 'mobile-ui-kit', name: 'Mobile App UI Kit', description: 'Native iOS/Android Designs, 25 Screens', price: 1490, category: 'Design', icon: 'mobile',
    features: ['25 Screens Mobile First', 'iOS Human Interface', 'Material Design 3', 'Animations-Specs', 'Asset-Export'],
    devInstructions: 'Designe ein vollstaendiges Mobile UI Kit mit 25 Screens (Onboarding, Auth, Hauptflows, Profil, Settings) fuer iOS und Android. Beachte HIG und Material 3, liefere Animations-Specs und exportierte Assets.',
    estimatedHours: 40, tags: ['ios', 'android', 'mobile'] },
  { id: 'landing-design', name: 'Landingpage Design', description: 'Hochkonvertierende Marketing-Page', price: 790, category: 'Design', icon: 'page',
    features: ['Hero, Features, Social Proof, CTA', 'Mobile-First', 'A/B-Test-Varianten', 'SEO-optimierte Strukturen', 'Conversion-Patterns'],
    devInstructions: 'Designe eine Landingpage mit Hero, Features-Showcase, Social Proof, Pricing/CTA und Footer. Mobile-first, A/B-Test-Varianten der Hero-Section, Conversion-orientiertes Layout.',
    estimatedHours: 18, tags: ['landing', 'conversion'], popular: true },
  { id: 'email-templates', name: 'Email-Template Pack', description: '10 responsive HTML-Email-Templates', price: 490, category: 'Design', icon: 'email',
    features: ['10 fertige Templates', 'Welcome, Reset, Receipt, ...', 'Outlook + Apple Mail tested', 'Dark Mode Support', 'MJML-Source'],
    devInstructions: 'Erstelle 10 responsive HTML-Email-Templates (Welcome, Password-Reset, Receipt, Newsletter, Re-Engagement etc.) in MJML, getestet in Outlook, Gmail, Apple Mail mit Dark-Mode-Support.',
    estimatedHours: 14, tags: ['email', 'transactional'] },
  { id: 'icon-set', name: 'Custom Icon Set', description: '50 maßgeschneiderte Icons im eigenen Stil', price: 590, category: 'Design', icon: 'icon',
    features: ['50 Icons SVG', 'Outline + Filled Varianten', 'React-Komponenten', 'Icon-Font-Export', 'Konsistenter Stil'],
    devInstructions: 'Designe 50 Custom-Icons im einheitlichen Stil (Outline + Filled), liefere SVGs, eine React-Icon-Bibliothek und einen Icon-Font.',
    estimatedHours: 22, tags: ['icons', 'svg'] },
  { id: 'illustrations', name: '10 Custom Illustrationen', description: 'Eigene Markenwelt mit individuellen Bildern', price: 990, category: 'Design', icon: 'illu',
    features: ['10 Vektor-Illustrationen', 'Empty States, Hero, Onboarding', 'Konsistenter Stil', 'Mehrere Größen', 'Editierbare Source-Files'],
    devInstructions: 'Erstelle 10 Custom-Illustrationen (Empty States, Hero-Visuals, Onboarding-Bilder) in einheitlichem Stil als Vektor (SVG + AI-Source).',
    estimatedHours: 28, tags: ['illustration', 'vector'] },
  { id: 'dark-mode', name: 'Dark-Mode-Theme', description: 'Vollständige Dark-Mode-Implementierung', price: 390, category: 'Design', icon: 'dark',
    features: ['Token-basiert', 'Auto-Detection', 'User-Override', 'Image-Anpassungen', 'Smooth Transitions'],
    devInstructions: 'Implementiere ein durchgaengiges Dark-Mode-Theme via CSS-Variablen / Token-System mit System-Erkennung und User-Override. Bilder, Schatten und Borders entsprechend anpassen.',
    estimatedHours: 12, tags: ['theme', 'dark', 'css'], popular: true },
  { id: 'micro-anim', name: 'Micro-Animations Pack', description: 'Subtile Animationen für mehr Lebendigkeit', price: 690, category: 'Design', icon: 'anim',
    features: ['Button-Hover-States', 'Page-Transitions', 'Loading-Spinner', 'Success-/Error-Cues', 'Framer Motion Setup'],
    devInstructions: 'Implementiere ein durchdachtes Micro-Animation-System mit Framer Motion: Button-States, Page-Transitions, Loading- und Success-Animationen. Beachte Performance und prefers-reduced-motion.',
    estimatedHours: 16, tags: ['animation', 'framer-motion'] },
  { id: 'print-design', name: 'Print-Material Design', description: 'Visitenkarten, Briefbogen, Flyer', price: 590, category: 'Design', icon: 'print',
    features: ['Visitenkarte 2-seitig', 'Briefbogen + Umschlag', 'Flyer A5', 'Druck-fertig (PDF/X-1a)', 'Bleed + Marken'],
    devInstructions: 'Designe Print-Materialien (Visitenkarte, Briefbogen, Umschlag, Flyer A5) druckfertig als PDF/X-1a inkl. Beschnitt und Passmarken.',
    estimatedHours: 14, tags: ['print', 'corporate'] },

  // ─────────────────────────── FRONTEND ───────────────────────────
  { id: 'auth-flow', name: 'Auth-Flow Komplett', description: 'Login, Register, Reset, OAuth (Google + Apple)', price: 690, category: 'Frontend', icon: 'auth',
    features: ['Login & Register UI', 'Passwort-Reset', 'Email-Verifikation', 'Google + Apple OAuth', 'Session-Management'],
    devInstructions: 'Baue ein vollstaendiges Auth-System mit Login, Registrierung, Passwort-Reset, Email-Verifikation und Google + Apple OAuth via Supabase Auth oder NextAuth. Sichere HttpOnly-Cookies, CSRF-Schutz.',
    estimatedHours: 16, tags: ['auth', 'oauth'], popular: true },
  { id: 'dashboard-widgets', name: 'Dashboard mit 5 Widgets', description: 'Kunden-Dashboard mit anpassbaren Widgets', price: 890, category: 'Frontend', icon: 'dashboard',
    features: ['5 Widget-Typen', 'Drag & Drop Layout', 'Responsive Grid', 'Pro-User-Speicherung', 'Realtime-Updates'],
    devInstructions: 'Implementiere ein anpassbares Dashboard mit 5 Widget-Typen (KPI, Liste, Chart, Aktivitaet, Quick Actions) auf Drag-and-Drop-Grid. Layout pro User in DB persistieren, Realtime-Updates via WebSocket.',
    estimatedHours: 24, tags: ['dashboard', 'widgets'] },
  { id: 'kanban-board', name: 'Kanban Board', description: 'Drag & Drop Tasks mit Columns + Tags', price: 690, category: 'Frontend', icon: 'kanban',
    features: ['Drag & Drop', 'Custom Columns', 'Task-Tags', 'Filter + Sort', 'Realtime-Sync'],
    devInstructions: 'Baue ein Drag-and-Drop Kanban-Board mit anpassbaren Columns, Task-Tags, Filtern und Realtime-Sync. Verwende dnd-kit oder react-beautiful-dnd.',
    estimatedHours: 20, tags: ['kanban', 'productivity'] },
  { id: 'form-builder', name: 'Form-Builder mit Validierung', description: 'Komplexe Formulare mit Conditional Logic', price: 590, category: 'Frontend', icon: 'form',
    features: ['Multi-Step Wizard', 'Conditional Fields', 'Live-Validierung', 'File-Upload', 'Auto-Save'],
    devInstructions: 'Implementiere einen flexiblen Form-Builder mit Conditional Logic (zeige Feld B wenn A=X), Multi-Step-Wizard, Live-Validierung via Zod, File-Upload und Auto-Save in IndexedDB.',
    estimatedHours: 22, tags: ['forms', 'validation'] },
  { id: 'file-upload', name: 'File-Upload mit Preview', description: 'Drag & Drop Upload mit Bildvorschau', price: 390, category: 'Frontend', icon: 'upload',
    features: ['Drag & Drop', 'Multi-File', 'Image-Preview', 'Upload-Fortschritt', 'Resize vor Upload'],
    devInstructions: 'Baue eine moderne File-Upload-Komponente mit Drag-and-Drop, Multi-File-Support, Bildvorschau, Fortschrittsanzeige und client-side Image-Resizing vor Upload.',
    estimatedHours: 10, tags: ['upload', 'files'] },
  { id: 'realtime-notif', name: 'Echtzeit-Notifications', description: 'In-App + Push-Notifications', price: 690, category: 'Frontend', icon: 'bell',
    features: ['In-App Toast/Center', 'Browser Push', 'Read/Unread', 'Filter & Settings', 'Sound-Cues'],
    devInstructions: 'Implementiere ein vollstaendiges Notification-System mit In-App Toasts, Notification-Center, Browser Push (Service Worker + VAPID) und User-Preferences fuer Sound + Channels.',
    estimatedHours: 18, tags: ['notifications', 'realtime'] },
  { id: 'wizard', name: 'Multi-Step Wizard', description: 'Onboarding oder Checkout in mehreren Schritten', price: 490, category: 'Frontend', icon: 'wizard',
    features: ['Beliebige Schritte', 'Validierung pro Step', 'Progress-Bar', 'Resume-Funktion', 'Mobile-friendly'],
    devInstructions: 'Erstelle einen wiederverwendbaren Multi-Step-Wizard mit Validierung pro Step, Progress-Bar, Resume-Funktion via localStorage und Mobile-First-Layout.',
    estimatedHours: 12, tags: ['wizard', 'onboarding'] },
  { id: 'autocomplete', name: 'Search mit Auto-Complete', description: 'Schnelle Suche mit Vorschlaegen', price: 390, category: 'Frontend', icon: 'search',
    features: ['Debounced Input', 'Keyboard-Navigation', 'Recent Searches', 'Highlighted Matches', 'Mobile-optimiert'],
    devInstructions: 'Implementiere eine performante Search-mit-Autocomplete-Komponente mit Debounce, Keyboard-Navigation, Recent Searches in localStorage und gehighlighteten Matches.',
    estimatedHours: 8, tags: ['search', 'ux'] },
  { id: 'pwa', name: 'PWA-Support', description: 'Progressive Web App mit Offline-Modus', price: 590, category: 'Frontend', icon: 'pwa',
    features: ['Installable', 'Offline-First', 'Service Worker', 'App Manifest', 'Push-Ready'],
    devInstructions: 'Mache die App zu einer installierbaren PWA mit Offline-First-Strategie (Workbox), App-Manifest mit Icons in allen Groessen, Push-Notification-Setup.',
    estimatedHours: 14, tags: ['pwa', 'offline'] },
  { id: 'data-table', name: 'Pro Data-Table', description: 'Sortier-, filter- und exportierbare Tabelle', price: 590, category: 'Frontend', icon: 'table',
    features: ['Sortierung', 'Filter pro Spalte', 'Pagination', 'CSV-Export', 'Spalten-Toggle'],
    devInstructions: 'Baue eine performante Pro-Data-Table mit Server-side Sortierung, Spalten-Filtern, Pagination, CSV-Export und User-anpassbaren Spalten.',
    estimatedHours: 16, tags: ['table', 'data'] },

  // ─────────────────────────── BACKEND ───────────────────────────
  { id: 'rest-api', name: 'REST API mit OpenAPI', description: 'Vollständige API mit Swagger-Doku', price: 1190, category: 'Backend', icon: 'api',
    features: ['CRUD-Endpoints', 'OpenAPI 3.1', 'Swagger UI', 'Auth-Middleware', 'Versionierung'],
    devInstructions: 'Baue eine RESTful API mit allen CRUD-Endpoints fuer die Domain, OpenAPI-3.1-Spezifikation, Swagger-UI, JWT-Auth-Middleware und semantische Versionierung.',
    estimatedHours: 30, tags: ['api', 'rest'] },
  { id: 'graphql-api', name: 'GraphQL API', description: 'Flexible API mit Schema + Subscriptions', price: 1390, category: 'Backend', icon: 'graphql',
    features: ['Type-safe Schema', 'Queries + Mutations', 'Subscriptions (WS)', 'DataLoader', 'GraphQL Playground'],
    devInstructions: 'Implementiere eine GraphQL-API mit type-safe Schema, Queries, Mutations, WebSocket-Subscriptions, DataLoader gegen N+1 und Apollo-Studio-Integration.',
    estimatedHours: 36, tags: ['graphql', 'api'] },
  { id: 'websocket', name: 'WebSocket-Server', description: 'Echtzeit-Kommunikation mit Rooms', price: 890, category: 'Backend', icon: 'ws',
    features: ['Room-System', 'Presence-Tracking', 'Auth-Integration', 'Auto-Reconnect', 'Skalierbar (Redis-Pub/Sub)'],
    devInstructions: 'Baue einen WebSocket-Server mit Rooms, Presence-Tracking, Auth-Integration und Redis-Pub/Sub fuer horizontale Skalierung.',
    estimatedHours: 24, tags: ['websocket', 'realtime'] },
  { id: 'cron-jobs', name: 'Cron-Jobs / Scheduling', description: 'Geplante Tasks mit Retry & Logging', price: 590, category: 'Backend', icon: 'cron',
    features: ['Cron-Syntax', 'Retry mit Backoff', 'Failure-Alerts', 'Job-History', 'Distributed Lock'],
    devInstructions: 'Implementiere ein Job-Scheduling-System mit Cron-Syntax, exponential Backoff, Job-History in DB, Failure-Alerts und distributed Locks gegen Doppelausfuehrung.',
    estimatedHours: 14, tags: ['cron', 'jobs'] },
  { id: 'storage-backend', name: 'File-Upload Backend (S3/R2)', description: 'Sichere Datei-Speicherung mit CDN', price: 690, category: 'Backend', icon: 'storage',
    features: ['Pre-signed URLs', 'Virus-Scan', 'CDN-Integration', 'Quota pro User', 'Bild-Optimierung'],
    devInstructions: 'Baue ein File-Upload-Backend mit S3/R2, Pre-signed URLs, ClamAV-Virus-Scan, CDN-Integration, Quota pro User und automatischer Bild-Optimierung (sharp).',
    estimatedHours: 18, tags: ['storage', 's3'] },
  { id: 'pdf-gen', name: 'PDF-Generierung', description: 'Rechnungen, Reports, Verträge als PDF', price: 590, category: 'Backend', icon: 'pdf',
    features: ['Template-System', 'Charts + Tabellen', 'Digitale Signatur', 'Batch-Export', 'Wasserzeichen'],
    devInstructions: 'Implementiere PDF-Generierung mit React-PDF oder Puppeteer fuer Rechnungen, Reports und Vertraege. Template-System, Charts, optional digitale Signatur.',
    estimatedHours: 14, tags: ['pdf', 'reports'] },
  { id: 'email-service', name: 'Email-Service Pro', description: 'Templates + Versand mit Tracking', price: 690, category: 'Backend', icon: 'email-svc',
    features: ['10 Templates', 'Versand via Resend/SES', 'Open + Click Tracking', 'Bounce-Handling', 'Unsubscribe-Mgmt'],
    devInstructions: 'Setze einen Email-Service mit Resend oder SES auf, 10 Templates (MJML), Open/Click-Tracking, Bounce-Handling und konformes Unsubscribe-Management.',
    estimatedHours: 16, tags: ['email', 'transactional'], popular: true },
  { id: 'webhooks', name: 'Webhook-Manager', description: 'Outbound + Inbound Webhooks mit Retry', price: 590, category: 'Backend', icon: 'hook',
    features: ['Signature-Verification', 'Retry-Logic', 'Delivery-Logs', 'Replay-Funktion', 'Event-Subscriptions'],
    devInstructions: 'Baue ein Webhook-System mit HMAC-Signatur, Retry mit exponential Backoff, Delivery-Logs, Replay-Funktion und User-konfigurierbaren Event-Subscriptions.',
    estimatedHours: 16, tags: ['webhooks', 'integrations'] },
  { id: 'rate-limit', name: 'Rate Limiting & Caching', description: 'API-Schutz + Response-Caching', price: 390, category: 'Backend', icon: 'rate',
    features: ['Per-User-Limits', 'Sliding Window', 'Redis-basiert', 'CDN-Cache', 'Stale-While-Revalidate'],
    devInstructions: 'Implementiere Rate Limiting mit Sliding Window (Redis), CDN-Cache-Headers und Stale-While-Revalidate fuer hochfrequente Endpoints.',
    estimatedHours: 8, tags: ['performance', 'security'] },
  { id: 'job-queue', name: 'Background Job Queue', description: 'Asynchrone Tasks mit Worker-System', price: 690, category: 'Backend', icon: 'queue',
    features: ['BullMQ / pg-boss', 'Worker-Pool', 'Job-Prioritaet', 'Dashboard', 'Failed-Job-Retry'],
    devInstructions: 'Baue eine Background-Job-Queue mit BullMQ oder pg-boss, Worker-Pool, Prioritaeten, Admin-Dashboard und Retry fuer failed jobs.',
    estimatedHours: 14, tags: ['queue', 'jobs'] },

  // ─────────────────────────── AI ───────────────────────────
  { id: 'ai-chatbot', name: 'AI Chatbot', description: 'Custom GPT/Claude für deine Plattform', price: 1190, category: 'AI', icon: 'bot',
    features: ['Eigene Knowledge Base', 'Multi-Turn-Konversation', 'Streaming-Antworten', 'Citations', 'Cost-Tracking'],
    devInstructions: 'Baue einen Custom-AI-Chatbot mit eigener Knowledge Base (Vector-DB), Multi-Turn-Memory, Streaming-Antworten, Source-Citations und Token-/Cost-Tracking pro User.',
    estimatedHours: 32, tags: ['ai', 'chatbot'], popular: true },
  { id: 'semantic-search', name: 'Semantic Search', description: 'Embeddings-basierte intelligente Suche', price: 890, category: 'AI', icon: 'sem',
    features: ['Vector Embeddings', 'pgvector / Pinecone', 'Hybrid Search (Keyword+Semantic)', 'Re-Ranking', 'Filter-Combo'],
    devInstructions: 'Implementiere Semantic Search mit OpenAI/Voyage Embeddings, pgvector als Index, Hybrid Search (Kombi aus Keyword + Semantic) und LLM-Re-Ranking der Top-Results.',
    estimatedHours: 24, tags: ['search', 'embeddings'] },
  { id: 'ai-image-gen', name: 'AI Image Generation', description: 'Bilder generieren via DALL-E / Stable Diffusion', price: 890, category: 'AI', icon: 'image-ai',
    features: ['Text-to-Image', 'Image-to-Image', 'Style-Presets', 'Bild-Galerie pro User', 'Cost-Limits'],
    devInstructions: 'Integriere AI Image Generation (DALL-E 3 / Stable Diffusion) mit Text-to-Image, Image-to-Image, Style-Presets, User-Galerie und Cost-Limits pro Account.',
    estimatedHours: 22, tags: ['ai', 'image'] },
  { id: 'voice-to-text', name: 'Voice-To-Text', description: 'Audio-Transkription mit Whisper', price: 690, category: 'AI', icon: 'voice',
    features: ['Whisper API', 'Speaker-Diarization', 'Mehrsprachig', 'Live-Transkription', 'Export Word/SRT'],
    devInstructions: 'Implementiere Audio-Transkription mit Whisper API, Speaker-Diarization, Multi-Language, optionaler Live-Transkription via WebSocket und Export als Word/SRT.',
    estimatedHours: 18, tags: ['ai', 'audio', 'whisper'] },
  { id: 'tts', name: 'Text-To-Speech', description: 'Natürliche Sprachausgabe in 30+ Sprachen', price: 590, category: 'AI', icon: 'tts',
    features: ['ElevenLabs / OpenAI Voice', '30+ Sprachen', 'Voice-Cloning (optional)', 'SSML-Support', 'MP3-Download'],
    devInstructions: 'Integriere Text-to-Speech via ElevenLabs oder OpenAI mit 30+ Sprachen, SSML, optionalem Voice-Cloning und MP3-Download.',
    estimatedHours: 12, tags: ['ai', 'voice'] },
  { id: 'ai-moderation', name: 'AI Content Moderation', description: 'Automatische Erkennung von problematischem Content', price: 590, category: 'AI', icon: 'moderate',
    features: ['Text + Bild Moderation', 'Custom-Regeln', 'Audit-Log', 'Review-Queue', 'Auto-Block'],
    devInstructions: 'Baue automatische Content-Moderation fuer Text und Bilder via OpenAI Moderation API + eigene Custom-Regeln, Review-Queue fuer Borderline-Cases und Audit-Log.',
    estimatedHours: 14, tags: ['ai', 'safety'] },
  { id: 'recommender', name: 'Recommendation Engine', description: 'Personalisierte Empfehlungen', price: 990, category: 'AI', icon: 'recom',
    features: ['Collaborative Filtering', 'Content-Based', 'Hybrid', 'Real-Time-Updates', 'A/B-Testing'],
    devInstructions: 'Implementiere eine Recommendation-Engine mit Hybrid-Ansatz (Collaborative + Content-Based), Real-Time-Updates und integriertem A/B-Testing-Framework.',
    estimatedHours: 28, tags: ['ai', 'ml'] },
  { id: 'rag-kb', name: 'RAG Knowledge Base', description: 'Frage-Antwort-System auf eigenen Dokumenten', price: 1390, category: 'AI', icon: 'rag',
    features: ['Doc-Ingestion (PDF/Web)', 'Chunking + Embeddings', 'RAG-Pipeline', 'Source-Linking', 'Update-on-Change'],
    devInstructions: 'Baue eine RAG-Pipeline: PDF/Web-Doc-Ingestion, semantisches Chunking, Embeddings in Vector-DB, Retrieval + LLM-Antwort mit Source-Links und Auto-Update bei Doc-Aenderungen.',
    estimatedHours: 36, tags: ['ai', 'rag'], popular: true },
  { id: 'ai-translation', name: 'AI-Translation', description: 'Hochwertige Übersetzung in 50+ Sprachen', price: 590, category: 'AI', icon: 'translate',
    features: ['DeepL + GPT Fallback', '50+ Sprachen', 'Glossar pro Kunde', 'Bulk-Uebersetzung', 'i18n-Export'],
    devInstructions: 'Integriere AI-Translation primaer via DeepL mit GPT-Fallback, Custom-Glossar pro Kunde, Bulk-Uebersetzung von JSON-Files und i18n-Export.',
    estimatedHours: 12, tags: ['ai', 'i18n'] },
  { id: 'predictive', name: 'Predictive Analytics', description: 'ML-Modelle für Forecasts und Klassifizierung', price: 1490, category: 'AI', icon: 'predict',
    features: ['Custom ML-Modell', 'Training-Pipeline', 'Feature Store', 'Model-Versioning', 'Monitoring'],
    devInstructions: 'Trainiere Custom-ML-Modelle (Forecasts oder Klassifizierung), baue Training-Pipeline, Feature Store, Model-Versioning und Performance-Monitoring auf.',
    estimatedHours: 50, tags: ['ml', 'analytics'] },

  // ─────────────────────────── MARKETING ───────────────────────────
  { id: 'seo-audit', name: 'SEO Audit & Optimierung', description: 'Vollständige technische SEO-Analyse + Fix', price: 790, category: 'Marketing', icon: 'seo',
    features: ['Technical SEO Audit', 'Core Web Vitals', 'Schema-Markup', 'XML-Sitemap', 'Robots.txt'],
    devInstructions: 'Fuehre einen vollstaendigen SEO-Audit durch (Lighthouse, Core Web Vitals), implementiere Schema.org-Markup, XML-Sitemap, korrekte robots.txt und liefere einen Maßnahmen-Report.',
    estimatedHours: 16, tags: ['seo', 'audit'], popular: true },
  { id: 'content-strategy', name: 'Content-Strategie 10 Artikel', description: 'Recherchierte und SEO-optimierte Artikel', price: 1490, category: 'Marketing', icon: 'content',
    features: ['10 Artikel à 1500 Wörter', 'Keyword-Recherche', 'On-Page-SEO', 'Internal Linking', 'CMS-fertig'],
    devInstructions: 'Erstelle eine Content-Strategie mit Keyword-Recherche und liefere 10 SEO-optimierte Artikel à 1500 Woerter mit Internal Linking, fertig zur Veroeffentlichung im CMS.',
    estimatedHours: 40, tags: ['content', 'seo'] },
  { id: 'newsletter', name: 'Newsletter-System', description: 'Subscribe + Mailchimp/Resend-Integration', price: 590, category: 'Marketing', icon: 'newsletter',
    features: ['Subscribe-Form', 'Double-Opt-In', 'Segmentierung', 'Analytics', 'Unsubscribe-Mgmt'],
    devInstructions: 'Baue ein Newsletter-System mit Double-Opt-In, Segmentierung nach Tags, Open/Click-Analytics und konformen Unsubscribe-Management.',
    estimatedHours: 12, tags: ['email', 'newsletter'] },
  { id: 'lead-magnet', name: 'Lead-Magnet-Funnel', description: 'PDF-Download gegen Email + Email-Sequenz', price: 690, category: 'Marketing', icon: 'lead',
    features: ['Landingpage', 'Lead-Form', 'PDF-Versand', '5-Email-Sequenz', 'CRM-Sync'],
    devInstructions: 'Setze einen Lead-Magnet-Funnel: Landingpage, Form, automatischer PDF-Versand, 5-Email-Sequenz und Sync zu CRM.',
    estimatedHours: 14, tags: ['marketing', 'leads'] },
  { id: 'ab-testing', name: 'A/B-Testing-Framework', description: 'Server-side oder Client-side Experiments', price: 690, category: 'Marketing', icon: 'ab',
    features: ['Variant-Splits', 'Statistische Signifikanz', 'Conversion-Tracking', 'Dashboard', 'Feature-Flags'],
    devInstructions: 'Implementiere ein A/B-Testing-Framework mit Variant-Splits, Conversion-Tracking, statistischer Signifikanz-Pruefung, Admin-Dashboard und Feature-Flag-Integration.',
    estimatedHours: 18, tags: ['ab-test', 'experiments'] },
  { id: 'tag-manager', name: 'Tag-Manager-Integration', description: 'GTM oder Plausible Events', price: 290, category: 'Marketing', icon: 'tag',
    features: ['GTM-Setup', 'Custom Events', 'DataLayer', 'Cookie-Compliant', 'Debug-Tools'],
    devInstructions: 'Integriere Google Tag Manager (oder Plausible Custom Events), DataLayer fuer Custom Events, DSGVO-konforme Cookie-Steuerung.',
    estimatedHours: 6, tags: ['analytics', 'gtm'] },
  { id: 'social-share', name: 'Social-Media-Sharing', description: 'OG-Images + Share-Buttons', price: 290, category: 'Marketing', icon: 'social',
    features: ['Dynamische OG-Images', 'Share-Buttons', 'Twitter Cards', 'LinkedIn Posts', 'Pinterest-Pin'],
    devInstructions: 'Implementiere dynamische Open-Graph-Images (zb @vercel/og), Share-Buttons fuer alle Plattformen, Twitter Cards und LinkedIn-Optimierung.',
    estimatedHours: 6, tags: ['social', 'sharing'] },
  { id: 'affiliate', name: 'Affiliate-System', description: 'Tracking + Auszahlungen für Partner', price: 1290, category: 'Marketing', icon: 'affiliate',
    features: ['Referral-Links', 'Conversion-Tracking', 'Auszahlungs-Mgmt', 'Partner-Dashboard', 'Cookie-Lifetime'],
    devInstructions: 'Baue ein Affiliate-System mit Referral-Links, Cookie-basiertem Tracking, Conversion-Attribution, Partner-Dashboard und automatisierten Auszahlungen.',
    estimatedHours: 32, tags: ['affiliate', 'tracking'] },
  { id: 'referral', name: 'Referral-Programm', description: 'User-Empfehlungen mit Reward', price: 690, category: 'Marketing', icon: 'referral',
    features: ['Personal Invite Links', 'Reward-System', 'Leaderboard', 'Email-Templates', 'Anti-Fraud'],
    devInstructions: 'Implementiere ein Referral-Programm mit personalisierten Invite-Links, automatischen Rewards (Credits/Discount), Leaderboard und Anti-Fraud-Checks.',
    estimatedHours: 16, tags: ['referral', 'growth'] },
  { id: 'cookie-consent', name: 'Cookie-Consent (DSGVO)', description: 'Rechtssicher mit Granular-Auswahl', price: 290, category: 'Marketing', icon: 'cookie',
    features: ['Granular-Consent', 'Audit-Log', 'TCF 2.2', 'Re-Consent-Trigger', 'Geo-Targeting'],
    devInstructions: 'Implementiere ein DSGVO-konformes Cookie-Consent-Banner mit granularer Kategorienauswahl, Audit-Log, TCF 2.2 und Re-Consent-Trigger bei Aenderung.',
    estimatedHours: 8, tags: ['gdpr', 'cookies'] },

  // ─────────────────────────── E-COMMERCE ───────────────────────────
  { id: 'stripe-subs', name: 'Stripe Subscriptions', description: 'Recurring Billing mit Plänen + Trials', price: 990, category: 'E-Commerce', icon: 'stripe',
    features: ['Multi-Plan', 'Trial-Period', 'Upgrade/Downgrade', 'Prorating', 'Invoice-PDFs'],
    devInstructions: 'Integriere Stripe Subscriptions mit mehreren Plaenen, Trial-Period, Upgrade/Downgrade mit Prorating und Invoice-PDFs via Customer Portal.',
    estimatedHours: 22, tags: ['stripe', 'billing'], popular: true },
  { id: 'shopping-cart', name: 'Shopping-Cart', description: 'Persistenter Warenkorb mit Mengen', price: 590, category: 'E-Commerce', icon: 'cart',
    features: ['Cross-Device-Sync', 'Mengen-Anpassung', 'Coupons', 'Versandkosten-Calc', 'Save for Later'],
    devInstructions: 'Baue einen persistenten Shopping-Cart mit Cross-Device-Sync, Mengen-Anpassung, Coupon-Eingabe, Live-Versandkosten und Save-for-Later.',
    estimatedHours: 14, tags: ['cart', 'ecommerce'] },
  { id: 'product-catalog', name: 'Produktkatalog mit Filtern', description: 'Listing mit Facetten-Filterung', price: 790, category: 'E-Commerce', icon: 'catalog',
    features: ['Facet-Filter', 'Sort-Options', 'Quick-View', 'Out-of-Stock-Handling', 'SEO-URLs'],
    devInstructions: 'Implementiere einen Produktkatalog mit Facetten-Filtern (Preis, Marke, Kategorie), Sort, Quick-View-Modal und SEO-freundlichen URLs.',
    estimatedHours: 18, tags: ['catalog', 'shop'] },
  { id: 'checkout', name: 'Checkout-Flow', description: '1-Step oder 3-Step Checkout', price: 890, category: 'E-Commerce', icon: 'checkout',
    features: ['Guest-Checkout', 'Adress-Validierung', 'Multi-Payment', 'Order-Bumps', 'Mobile-First'],
    devInstructions: 'Baue einen optimierten Checkout mit Guest-Option, Adress-Validierung, Stripe + Apple Pay / Google Pay, Order-Bumps und Mobile-First-Layout.',
    estimatedHours: 24, tags: ['checkout', 'conversion'] },
  { id: 'order-mgmt', name: 'Bestellverwaltung', description: 'Admin-Tool für Orders', price: 690, category: 'E-Commerce', icon: 'orders',
    features: ['Status-Workflow', 'Refunds', 'Notes', 'Print-Labels', 'Export'],
    devInstructions: 'Erstelle ein Order-Management-Backend mit Status-Workflow (Paid → Processing → Shipped), Refund-Funktion, internen Notes, Versandlabel-Druck und Export.',
    estimatedHours: 18, tags: ['admin', 'orders'] },
  { id: 'shipping', name: 'Versand-Integration', description: 'DHL/UPS Labels + Tracking', price: 690, category: 'E-Commerce', icon: 'ship',
    features: ['Label-Generierung', 'Echtzeit-Tracking', 'Multi-Carrier', 'Versandkosten-API', 'Customs-Forms'],
    devInstructions: 'Integriere DHL/UPS/Hermes APIs fuer Label-Generierung, Echtzeit-Tracking, automatische Versandkosten und Zollformulare bei Auslandsversand.',
    estimatedHours: 18, tags: ['shipping', 'logistics'] },
  { id: 'coupons', name: 'Gutschein-System', description: 'Percent/Fixed + Conditions', price: 390, category: 'E-Commerce', icon: 'coupon',
    features: ['Percent + Fixed Discount', 'Min-Order', 'Usage-Limits', 'BOGO', 'Stackable'],
    devInstructions: 'Baue ein Gutschein-System mit Percent/Fixed Discount, Mindestbestellwert, Usage-Limits, BOGO-Aktionen und stackbaren Codes.',
    estimatedHours: 10, tags: ['coupons', 'promo'] },
  { id: 'inventory', name: 'Lager-Verwaltung', description: 'Stock-Tracking mit Low-Stock-Alerts', price: 690, category: 'E-Commerce', icon: 'inventory',
    features: ['Multi-Warehouse', 'Low-Stock-Alerts', 'Reservation-System', 'Audit-Trail', 'CSV-Import'],
    devInstructions: 'Implementiere Lager-Verwaltung mit Multi-Warehouse, Low-Stock-Alerts, Reservierung waehrend Checkout, vollstaendigem Audit-Trail und CSV-Import.',
    estimatedHours: 20, tags: ['inventory', 'stock'] },
  { id: 'multi-currency', name: 'Multi-Währung', description: 'Live-Wechselkurse + Lokalisierung', price: 490, category: 'E-Commerce', icon: 'currency',
    features: ['Live FX-Rates', 'Currency-Switcher', 'Pro-Region-Pricing', 'Tax-Aware', 'Reporting'],
    devInstructions: 'Implementiere Multi-Currency mit Live-Wechselkursen, Currency-Switcher, optionaler Pro-Region-Preisliste und Tax-Aware-Pricing.',
    estimatedHours: 12, tags: ['i18n', 'currency'] },
  { id: 'tax-calc', name: 'Steuer-Berechnung', description: 'EU MwSt + US Sales Tax', price: 590, category: 'E-Commerce', icon: 'tax',
    features: ['VIES-Validierung', 'EU OSS', 'US Sales Tax', 'B2B Reverse Charge', 'Audit-Reports'],
    devInstructions: 'Implementiere automatische Steuer-Berechnung fuer EU (MwSt mit OSS, VIES-Validierung, B2B Reverse Charge) und US (Sales Tax via TaxJar/Avalara).',
    estimatedHours: 16, tags: ['tax', 'compliance'] },

  // ─────────────────────────── ANALYTICS ───────────────────────────
  { id: 'plausible', name: 'Plausible / PostHog Setup', description: 'Privacy-First Web Analytics', price: 290, category: 'Analytics', icon: 'plausible',
    features: ['Plausible / PostHog', 'Custom Events', 'Goals', 'UTM-Tracking', 'Cookie-frei'],
    devInstructions: 'Setze Plausible oder PostHog auf, definiere Custom-Events, Goals, UTM-Tracking und integriere ohne Cookies.',
    estimatedHours: 6, tags: ['analytics', 'privacy'] },
  { id: 'analytics-dashboard', name: 'Custom Analytics-Dashboard', description: 'Eigene Metriken in Echtzeit', price: 990, category: 'Analytics', icon: 'analytics',
    features: ['Eigene KPIs', 'Custom Charts', 'Filter + Drill-Down', 'Export', 'Realtime-Updates'],
    devInstructions: 'Baue ein Custom Analytics-Dashboard mit eigenen KPIs, interaktiven Charts (Recharts), Filter, Drill-Down, Export und Realtime-Updates.',
    estimatedHours: 28, tags: ['dashboard', 'analytics'] },
  { id: 'heatmap', name: 'Heatmap-Tracking', description: 'Click-Maps + Scroll-Maps', price: 390, category: 'Analytics', icon: 'heatmap',
    features: ['Click-Maps', 'Scroll-Maps', 'Session-Replay', 'Funnel-Analyse', 'Device-Filter'],
    devInstructions: 'Integriere Heatmap-Tracking via Hotjar oder PostHog mit Click-Maps, Scroll-Maps, optional Session-Replay und Device-Filter.',
    estimatedHours: 6, tags: ['heatmap', 'ux'] },
  { id: 'user-journey', name: 'User-Journey-Analyse', description: 'Trichter und Pfade durch die App', price: 690, category: 'Analytics', icon: 'journey',
    features: ['Funnel-Definition', 'Drop-Off-Analyse', 'Pfad-Visualisierung', 'Cohort-Vergleich', 'Auto-Insights'],
    devInstructions: 'Implementiere User-Journey-Tracking mit Funnel-Definition, Drop-Off-Analyse, Pfad-Visualisierung, Cohort-Vergleich und Auto-Insights via PostHog.',
    estimatedHours: 14, tags: ['journey', 'funnel'] },
  { id: 'data-export', name: 'Datenexport CSV/Excel', description: 'Filterbare Exports für Reporting', price: 290, category: 'Analytics', icon: 'export',
    features: ['Filter-basierter Export', 'CSV + Excel', 'Scheduled Exports', 'Email-Versand', 'API-Endpoint'],
    devInstructions: 'Implementiere Datenexport mit Filterbare CSV- und Excel-Exports, geplante Exports per Cron mit Email-Versand und API-Endpoint fuer Power-User.',
    estimatedHours: 8, tags: ['export', 'reporting'] },
  { id: 'reporting', name: 'Reporting-System', description: 'Automatisierte Reports per Email', price: 690, category: 'Analytics', icon: 'report',
    features: ['Templates', 'Scheduled Send', 'PDF-Export', 'Multi-Recipient', 'Branded'],
    devInstructions: 'Baue ein Reporting-System mit anpassbaren Templates, Scheduled-Send (taeglich/woechentlich), PDF-Export, Multi-Recipient und Custom-Branding.',
    estimatedHours: 16, tags: ['reports', 'automation'] },
  { id: 'data-viz', name: 'Datenvisualisierung Pro', description: 'Interactive Charts mit D3 oder Recharts', price: 590, category: 'Analytics', icon: 'viz',
    features: ['10+ Chart-Typen', 'Animations', 'Tooltip-Custom', 'Responsive', 'Theme-Aware'],
    devInstructions: 'Erstelle eine Datenvisualisierungs-Bibliothek mit 10+ Chart-Typen (Line, Bar, Area, Pie, Radar, Sankey, ...), Animations, custom Tooltips und Theme-Awareness.',
    estimatedHours: 18, tags: ['charts', 'd3'] },
  { id: 'realtime-logs', name: 'Real-time Logs', description: 'Live-Logging mit Filter & Search', price: 390, category: 'Analytics', icon: 'logs',
    features: ['Live-Stream', 'Search + Filter', 'Log-Levels', 'Persistent Storage', 'Slack-Alerts'],
    devInstructions: 'Implementiere Real-time Logs mit Live-Stream, Search/Filter, Log-Levels, persistentem Storage (S3/BigQuery) und Slack-Alerts bei Errors.',
    estimatedHours: 10, tags: ['logs', 'monitoring'] },
  { id: 'kpi-tracker', name: 'KPI-Tracker', description: 'OKRs und KPIs mit Alarmen', price: 590, category: 'Analytics', icon: 'kpi',
    features: ['Custom KPIs', 'Trend-Analyse', 'Alerts', 'Goal-Tracking', 'Sharing'],
    devInstructions: 'Baue einen KPI-Tracker mit Custom-KPIs, Trend-Analyse, Alerts bei Abweichungen, OKR-Goal-Tracking und Sharing-Funktion.',
    estimatedHours: 14, tags: ['kpi', 'okr'] },
  { id: 'session-replay', name: 'Session Replay', description: 'Aufzeichnungen für UX-Forschung', price: 590, category: 'Analytics', icon: 'replay',
    features: ['Privacy-Masking', 'Console-Logs', 'Network-Trace', 'Filter', 'GDPR-konform'],
    devInstructions: 'Integriere Session-Replay (rrweb / PostHog) mit Privacy-Masking sensibler Felder, Console-Logs, Network-Trace und GDPR-konformer Speicherung.',
    estimatedHours: 10, tags: ['replay', 'ux'] },

  // ─────────────────────────── MOBILE ───────────────────────────
  { id: 'rn-app', name: 'React Native App', description: 'iOS + Android aus einer Codebase', price: 2990, category: 'Mobile', icon: 'rn',
    features: ['Expo Setup', 'Navigation-Stack', 'iOS + Android', 'Push-Ready', 'OTA-Updates'],
    devInstructions: 'Baue eine React Native App mit Expo, Navigation-Stack, iOS + Android Build, Push-Notification-Setup und OTA-Updates via EAS.',
    estimatedHours: 80, tags: ['react-native', 'mobile'], popular: true },
  { id: 'push-notif', name: 'Push-Notifications', description: 'iOS + Android + Web Push', price: 590, category: 'Mobile', icon: 'push',
    features: ['APNs + FCM', 'Topic-Subscribe', 'Scheduled Pushes', 'Rich Media', 'Action-Buttons'],
    devInstructions: 'Implementiere Push-Notifications fuer iOS (APNs), Android (FCM) und Web mit Topic-Subscribe, Scheduled-Pushes, Rich Media (Bilder) und Action-Buttons.',
    estimatedHours: 16, tags: ['push', 'mobile'] },
  { id: 'offline-sync', name: 'Offline-Sync', description: 'App funktioniert auch offline', price: 990, category: 'Mobile', icon: 'offline',
    features: ['SQLite/WatermelonDB', 'Conflict-Resolution', 'Background-Sync', 'Optimistic-UI', 'Queue-Replay'],
    devInstructions: 'Implementiere Offline-First-Architektur mit SQLite/WatermelonDB, Conflict-Resolution-Strategie, Background-Sync und Queue-Replay fuer pending mutations.',
    estimatedHours: 32, tags: ['offline', 'sync'] },
  { id: 'biometric', name: 'Biometrische Auth', description: 'Face ID / Touch ID', price: 290, category: 'Mobile', icon: 'biometric',
    features: ['Face ID + Touch ID', 'Fallback Passcode', 'Secure Enclave', 'Auto-Lock', 'iOS + Android'],
    devInstructions: 'Integriere Biometrische Authentifizierung (Face ID, Touch ID, Android Biometric) mit sicherem Storage in Secure Enclave / Keystore und Fallback auf Passcode.',
    estimatedHours: 6, tags: ['biometric', 'auth'] },
  { id: 'app-store', name: 'App-Store-Listings', description: 'Screenshots, Description, ASO', price: 590, category: 'Mobile', icon: 'store',
    features: ['Screenshots iOS+Android', 'App-Description', 'Keywords (ASO)', 'Preview-Video', 'Localization'],
    devInstructions: 'Erstelle App-Store-Listings: Screenshots fuer alle Geraete-Groessen, Description, ASO-Keywords, optionales Preview-Video und Lokalisierung in Top-Sprachen.',
    estimatedHours: 12, tags: ['aso', 'app-store'] },
  { id: 'iap', name: 'In-App-Purchases', description: 'iOS + Android Subscriptions/Coins', price: 990, category: 'Mobile', icon: 'iap',
    features: ['iOS StoreKit', 'Android Billing', 'Receipt-Validation', 'RevenueCat-Integration', 'Restore-Purchase'],
    devInstructions: 'Integriere In-App-Purchases via RevenueCat fuer iOS (StoreKit 2) und Android Billing v6, Receipt-Validation, Restore-Purchase und Subscriptions.',
    estimatedHours: 22, tags: ['iap', 'monetization'] },
  { id: 'deep-link', name: 'Deep-Linking', description: 'Universal Links + App Links', price: 290, category: 'Mobile', icon: 'link',
    features: ['Universal Links iOS', 'App Links Android', 'Branch.io / Firebase', 'Defer-Deep-Linking', 'Tracking'],
    devInstructions: 'Setze Deep-Linking via Universal Links (iOS) und App Links (Android), optional via Branch.io oder Firebase Dynamic Links mit Defer-Deep-Linking und Tracking.',
    estimatedHours: 6, tags: ['deeplink', 'mobile'] },
  { id: 'native-camera', name: 'Native Camera + Photos', description: 'Foto-/Video-Capture mit Editor', price: 590, category: 'Mobile', icon: 'camera',
    features: ['Photo + Video Capture', 'Bibliothek-Picker', 'Crop + Filters', 'Compression', 'Permissions-Flow'],
    devInstructions: 'Implementiere native Camera + Photos mit Foto/Video-Capture, Bibliothek-Picker, Crop, simple Filters, Compression vor Upload und sauberem Permissions-Flow.',
    estimatedHours: 14, tags: ['camera', 'media'] },
  { id: 'native-maps', name: 'Native Maps', description: 'MapKit + Google Maps mit Marker', price: 590, category: 'Mobile', icon: 'maps',
    features: ['MapKit + Google Maps', 'Custom Marker', 'Cluster', 'Geocoding', 'Routing'],
    devInstructions: 'Integriere native Maps (MapKit auf iOS, Google Maps auf Android) mit Custom Markern, Clustering, Geocoding und Routing.',
    estimatedHours: 14, tags: ['maps', 'location'] },
  { id: 'bg-tasks', name: 'Background Tasks', description: 'Sync auch wenn App im Hintergrund', price: 590, category: 'Mobile', icon: 'bgtask',
    features: ['BG Fetch', 'BG Processing', 'Silent Push', 'Battery-Aware', 'iOS + Android'],
    devInstructions: 'Implementiere Background Tasks fuer Sync, Daten-Refresh und stille Push-Reaktionen, Battery-Aware mit System-Constraints auf iOS und Android.',
    estimatedHours: 14, tags: ['background', 'mobile'] },

  // ─────────────────────────── DEVOPS ───────────────────────────
  { id: 'cicd', name: 'CI/CD Pipeline', description: 'GitHub Actions mit Tests + Deploy', price: 590, category: 'DevOps', icon: 'cicd',
    features: ['GitHub Actions', 'Lint + Test + Build', 'Auto-Deploy', 'Preview-Envs', 'Slack-Notifications'],
    devInstructions: 'Baue eine vollstaendige CI/CD-Pipeline via GitHub Actions: Lint, Test, Build, Auto-Deploy zu Production, Preview-Envs pro PR und Slack-Notifications.',
    estimatedHours: 12, tags: ['cicd', 'github-actions'], popular: true },
  { id: 'monitoring', name: 'Monitoring & Alerting', description: 'Uptime + Error-Tracking + Alerts', price: 690, category: 'DevOps', icon: 'monitor',
    features: ['Uptime-Monitoring', 'Sentry-Integration', 'Custom-Metrics', 'PagerDuty-Alerts', 'Status-Page'],
    devInstructions: 'Setze Monitoring auf: Uptime via Better Stack/Pingdom, Sentry fuer Error-Tracking, Custom-Metrics, PagerDuty-Alerts und oeffentliche Status-Page.',
    estimatedHours: 14, tags: ['monitoring', 'sentry'] },
  { id: 'logging', name: 'Centralized Logging', description: 'Strukturierte Logs in Loki/Datadog', price: 590, category: 'DevOps', icon: 'log',
    features: ['Strukturiertes JSON', 'Loki/Datadog', 'Trace-Korrelation', 'Log-Retention', 'Search-UI'],
    devInstructions: 'Implementiere zentralisiertes Logging mit strukturierten JSON-Logs in Loki oder Datadog, Trace-Korrelation, Retention-Policy und durchsuchbarer UI.',
    estimatedHours: 12, tags: ['logging', 'observability'] },
  { id: 'backups', name: 'Backup-Strategie', description: 'Automatische Backups + Restore-Test', price: 590, category: 'DevOps', icon: 'backup',
    features: ['DB-Backups taeglich', 'Off-Site Storage', 'Point-in-Time-Recovery', 'Automatischer Restore-Test', 'Verschluesselt'],
    devInstructions: 'Implementiere Backup-Strategie mit taeglichen verschluesselten DB-Backups in off-site Storage, Point-in-Time-Recovery und automatischen Restore-Tests.',
    estimatedHours: 10, tags: ['backup', 'recovery'] },
  { id: 'autoscale', name: 'Auto-Scaling', description: 'Skaliert automatisch unter Last', price: 990, category: 'DevOps', icon: 'scale',
    features: ['Horizontal Scale', 'CPU/Memory-basiert', 'Min/Max-Limits', 'Cost-Aware', 'Load-Tests'],
    devInstructions: 'Konfiguriere Auto-Scaling auf der Hosting-Plattform (Vercel/Fly/Kubernetes) basierend auf CPU/Memory mit Min/Max-Limits, Cost-Awareness und initialen Load-Tests.',
    estimatedHours: 16, tags: ['scaling', 'k8s'] },
  { id: 'cdn', name: 'CDN-Setup', description: 'Cloudflare oder Vercel Edge Network', price: 290, category: 'DevOps', icon: 'cdn',
    features: ['Asset-Caching', 'Edge-Functions', 'Bild-Optimierung', 'WAF-Schutz', 'Cache-Purge'],
    devInstructions: 'Setze CDN via Cloudflare oder Vercel Edge: Asset-Caching, Bild-Optimierung, optionale Edge-Functions und WAF-Schutz.',
    estimatedHours: 6, tags: ['cdn', 'cloudflare'] },
  { id: 'ddos-protect', name: 'DDoS-Schutz', description: 'Automatische Mitigation', price: 390, category: 'DevOps', icon: 'shield',
    features: ['Cloudflare DDoS', 'Rate-Limiting', 'Bot-Detection', 'Challenge-Pages', 'Audit-Logs'],
    devInstructions: 'Aktiviere DDoS-Schutz via Cloudflare mit Rate-Limiting, Bot-Detection, Challenge-Pages bei Verdacht und durchgaengiger Audit-Logs.',
    estimatedHours: 6, tags: ['security', 'ddos'] },
  { id: 'ssl', name: 'SSL + HSTS', description: 'A+ SSL Labs Rating', price: 190, category: 'DevOps', icon: 'ssl',
    features: ['Let s Encrypt Auto-Renew', 'TLS 1.3', 'HSTS-Preload', 'CSP-Header', 'A+ Rating'],
    devInstructions: 'Konfiguriere SSL/TLS mit Auto-Renew via Let s Encrypt, TLS 1.3, HSTS mit Preload, sinnvolle CSP-Header und ziel A+ auf SSL Labs.',
    estimatedHours: 4, tags: ['ssl', 'tls'] },
  { id: 'multi-region', name: 'Multi-Region-Deployment', description: 'EU + US Region für Latenz', price: 1490, category: 'DevOps', icon: 'region',
    features: ['EU + US Regions', 'Geo-DNS', 'Multi-Region-DB', 'Failover', 'Replikation-Lag-Monitor'],
    devInstructions: 'Deploye die App in mehreren Regionen (EU + US) mit Geo-DNS, Multi-Region-DB-Replikation, automatischem Failover und Lag-Monitoring.',
    estimatedHours: 36, tags: ['multi-region', 'ha'] },
  { id: 'disaster-recovery', name: 'Disaster-Recovery-Plan', description: 'Runbook + RTO/RPO definiert', price: 590, category: 'DevOps', icon: 'disaster',
    features: ['Runbook', 'RTO/RPO Definition', 'Failover-Tests', 'Comm-Plan', 'Post-Mortem-Template'],
    devInstructions: 'Erstelle einen Disaster-Recovery-Plan mit Runbook, klaren RTO/RPO-Zielen, regelmaessigen Failover-Tests, Kommunikations-Plan und Post-Mortem-Template.',
    estimatedHours: 12, tags: ['disaster', 'runbook'] },

  // ─────────────────────────── SECURITY ───────────────────────────
  { id: 'pentest', name: 'Penetration-Test', description: 'Externer Security-Test mit Report', price: 1990, category: 'Security', icon: 'pentest',
    features: ['OWASP Top 10', 'Manuelle Tests', 'Severity-Rating', 'Re-Test inklusive', 'Report'],
    devInstructions: 'Beauftrage oder fuehre einen Penetration-Test durch (OWASP Top 10), manuell + automatisiert, mit Severity-Ratings, Re-Test nach Fixes und finalem Report.',
    estimatedHours: 40, tags: ['security', 'pentest'], popular: true },
  { id: 'security-audit', name: 'Security Audit', description: 'Code + Infrastruktur Review', price: 1290, category: 'Security', icon: 'audit',
    features: ['Code-Review', 'Dependency-Audit', 'Infra-Review', 'Threat-Model', 'Report mit Massnahmen'],
    devInstructions: 'Fuehre einen umfassenden Security-Audit durch: statische Code-Analyse, Dependency-Audit, Infrastruktur-Review, Threat-Modeling und Massnahmen-Report.',
    estimatedHours: 30, tags: ['security', 'audit'] },
  { id: 'gdpr', name: 'DSGVO-Compliance', description: 'Vollständige Compliance + Doku', price: 990, category: 'Security', icon: 'gdpr',
    features: ['Datenschutz-Erklaerung', 'AVV/DPA', 'Cookie-Consent', 'TOM', 'DSGVO-Datenexport/-loeschung'],
    devInstructions: 'Stelle vollstaendige DSGVO-Compliance her: Datenschutz-Erklaerung, AVV mit Subdienstleistern, Cookie-Consent, TOM-Doku, User-Datenexport und -loeschung.',
    estimatedHours: 22, tags: ['gdpr', 'compliance'] },
  { id: '2fa', name: '2-Faktor-Authentifizierung', description: 'TOTP + Recovery-Codes', price: 390, category: 'Security', icon: '2fa',
    features: ['TOTP (Google Auth)', 'Backup-Codes', 'WebAuthn (optional)', 'Force-2FA-Policy', 'Recovery-Flow'],
    devInstructions: 'Implementiere 2FA mit TOTP (RFC 6238), 8 Backup-Codes, optionalem WebAuthn fuer Sicherheits-Keys, optionaler Force-2FA-Policy und sicherem Recovery-Flow.',
    estimatedHours: 12, tags: ['2fa', 'security'] },
  { id: 'sso', name: 'Single Sign-On (SSO)', description: 'SAML + OIDC für Enterprise', price: 1290, category: 'Security', icon: 'sso',
    features: ['SAML 2.0', 'OIDC', 'JIT-Provisioning', 'SCIM Sync', 'Auth0/WorkOS-Setup'],
    devInstructions: 'Integriere Enterprise SSO via WorkOS oder Auth0 mit SAML 2.0 + OIDC, Just-In-Time-Provisioning und SCIM-Sync fuer User-Lifecycle.',
    estimatedHours: 22, tags: ['sso', 'enterprise'] },
  { id: 'audit-log', name: 'Audit-Log', description: 'Wer hat wann was gemacht', price: 490, category: 'Security', icon: 'auditlog',
    features: ['Tamper-Proof', 'Filterbar', 'Export', 'Retention-Policy', 'Admin-UI'],
    devInstructions: 'Implementiere ein Tamper-Proof Audit-Log fuer alle sicherheitsrelevanten Aktionen, filterbar in Admin-UI, exportierbar und mit Retention-Policy.',
    estimatedHours: 12, tags: ['audit', 'compliance'] },
  { id: 'encryption', name: 'Daten-Verschlüsselung', description: 'At-Rest + In-Transit + Field-Level', price: 690, category: 'Security', icon: 'crypt',
    features: ['Field-Level-Encryption', 'KMS-Integration', 'Key-Rotation', 'Search-able Encryption', 'Doku'],
    devInstructions: 'Implementiere Verschluesselung at-rest, in-transit und Field-Level fuer sensible Felder via KMS, mit Key-Rotation und durchsuchbarer Verschluesselung.',
    estimatedHours: 18, tags: ['encryption', 'kms'] },
  { id: 'data-export-gdpr', name: 'GDPR Data-Export', description: 'User exportiert seine Daten', price: 290, category: 'Security', icon: 'export-gdpr',
    features: ['Self-Service-Export', 'Alle Daten in JSON+CSV', 'Email-Versand', 'Verschluesselt', 'Audit-Log'],
    devInstructions: 'Baue Self-Service-DSGVO-Datenexport: User triggert, Hintergrund-Job sammelt alle Daten, schickt verschluesseltes Archiv per Email, Aktion im Audit-Log.',
    estimatedHours: 8, tags: ['gdpr', 'export'] },
  { id: 'cookie-mgr', name: 'Cookie-Manager', description: 'TCF 2.2 Konforme Verwaltung', price: 290, category: 'Security', icon: 'cookie-mgr',
    features: ['TCF 2.2', 'Granular-Consent', 'Geo-Targeting', 'Re-Consent-Trigger', 'Analytics'],
    devInstructions: 'Implementiere TCF-2.2-konformen Cookie-Manager mit granularer Auswahl, Geo-Targeting (DSGVO nur in EU), Re-Consent bei Aenderungen und Consent-Analytics.',
    estimatedHours: 8, tags: ['gdpr', 'cookie'] },
  { id: 'bug-bounty', name: 'Bug-Bounty-Programm', description: 'Setup auf HackerOne / Intigriti', price: 590, category: 'Security', icon: 'bug',
    features: ['Programm-Doku', 'Scope-Definition', 'Reward-Tiers', 'Triage-Workflow', 'PR + Onboarding'],
    devInstructions: 'Richte ein Bug-Bounty-Programm auf HackerOne oder Intigriti ein: Programm-Doku, Scope, Reward-Tiers, Triage-Workflow und Researcher-Onboarding.',
    estimatedHours: 14, tags: ['bug-bounty', 'security'] },

  // ─────────────────────────── DESIGN — ERWEITERT ───────────────────────────
  { id: 'wireframes', name: 'Wireframe-Pack', description: '10 Low-Fidelity Wireframes für UX-Tests', price: 390, category: 'Design', icon: 'wire',
    features: ['10 Wireframes', 'User-Flow-Diagramme', 'Klickbarer Prototyp', 'Annotations', 'Figma-Source'],
    devInstructions: 'Erstelle 10 Low-Fidelity Wireframes mit User-Flow-Diagrammen und einem klickbaren Prototyp in Figma fuer fruehe UX-Tests.',
    estimatedHours: 12, tags: ['wireframe', 'ux'] },
  { id: 'logo-refresh', name: 'Logo Refresh', description: 'Bestehendes Logo modernisieren', price: 490, category: 'Design', icon: 'refresh',
    features: ['3 Vorschlaege', 'Trend-Recherche', 'Final-Logo Vektor', 'Anwendungsbeispiele', 'Migrations-Plan'],
    devInstructions: 'Modernisiere das bestehende Logo mit 3 Vorschlaegen, Trend-Recherche, finalem Vektor und Migrations-Plan fuer alle bestehenden Touchpoints.',
    estimatedHours: 14, tags: ['logo', 'rebrand'] },
  { id: 'style-guide', name: 'Style Guide PDF', description: '20-seitiger Brand Style Guide', price: 390, category: 'Design', icon: 'guide',
    features: ['Logo-Verwendung', 'Farb-System', 'Typografie', 'Tone of Voice', 'Bildwelt'],
    devInstructions: 'Verfasse einen 20-seitigen Style Guide als PDF mit Logo-Verwendung, Farb- und Typografie-System, Tone of Voice und Bildwelt-Richtlinien.',
    estimatedHours: 12, tags: ['guide', 'brand'] },
  { id: 'ux-audit', name: 'UX-Audit', description: 'Heuristische Analyse + Empfehlungen', price: 690, category: 'Design', icon: 'ux',
    features: ['Nielsen Heuristics', 'User-Flow-Analyse', 'Pain-Points', 'Quick-Wins', 'Prioritisierung'],
    devInstructions: 'Fuehre einen UX-Audit nach Nielsen-Heuristiken durch, identifiziere Pain-Points, dokumentiere Quick-Wins und priorisiere Handlungsempfehlungen.',
    estimatedHours: 16, tags: ['audit', 'ux'] },
  { id: 'animation-storyboard', name: 'Animation Storyboard', description: 'Storyboard für Hero-Animation oder Erklaervideo', price: 590, category: 'Design', icon: 'storyboard',
    features: ['Frame-by-Frame', 'Lottie-fertig', 'Timing-Plan', 'Sound-Sync-Notes', 'After-Effects-Source'],
    devInstructions: 'Entwirf ein Animation-Storyboard frame-by-frame inkl. Timing-Plan, Lottie-Export und After-Effects-Source.',
    estimatedHours: 16, tags: ['animation', 'video'] },

  // ─────────────────────────── FRONTEND — ERWEITERT ───────────────────────────
  { id: 'theme-switcher', name: 'Theme-Switcher', description: 'Mehrere Themes mit Live-Preview', price: 290, category: 'Frontend', icon: 'theme',
    features: ['Multi-Theme', 'Live-Preview', 'User-Pref persistent', 'Theme-Tokens', 'Custom-Theme-Builder'],
    devInstructions: 'Baue einen Theme-Switcher mit Live-Preview, Token-System fuer Light/Dark/Custom und User-Preference persistiert in localStorage.',
    estimatedHours: 8, tags: ['theme', 'tokens'] },
  { id: 'tour', name: 'Onboarding-Tour', description: 'Geführte Tour für neue Nutzer', price: 390, category: 'Frontend', icon: 'tour',
    features: ['Step-by-Step', 'Highlight-Spotlight', 'Skip + Resume', 'Pro-User-Tracking', 'Mehrsprachig'],
    devInstructions: 'Implementiere eine geführte Onboarding-Tour mit Step-by-Step-Spotlights, Skip/Resume-Logik, Pro-User-Tracking und i18n.',
    estimatedHours: 10, tags: ['onboarding', 'tour'] },
  { id: 'i18n', name: 'Internationalisierung (i18n)', description: 'Mehrsprachigkeit mit dynamischem Lade-Mechanismus', price: 590, category: 'Frontend', icon: 'i18n',
    features: ['next-intl Setup', 'Sprach-Erkennung', 'Lazy-Loading der Locales', 'Fallback-Strategie', '5 Sprachen'],
    devInstructions: 'Implementiere i18n mit next-intl, Sprach-Erkennung, Lazy-Loading der Locales, sinnvoller Fallback-Strategie und 5 Sprachen vorbereitet.',
    estimatedHours: 14, tags: ['i18n', 'l10n'] },
  { id: 'a11y-audit', name: 'Accessibility-Audit', description: 'WCAG 2.2 AA Compliance', price: 690, category: 'Frontend', icon: 'a11y',
    features: ['WCAG 2.2 AA', 'Screen-Reader-Tests', 'Keyboard-Navigation', 'Color-Contrast', 'Massnahmen-Report'],
    devInstructions: 'Fuehre einen WCAG-2.2-AA-Audit durch, teste mit Screen-Reader, korrigiere Keyboard-Navigation und Kontraste, liefere Massnahmen-Report.',
    estimatedHours: 18, tags: ['a11y', 'wcag'] },
  { id: 'component-lib', name: 'Component-Library Plus', description: '15 zusätzliche UI-Komponenten', price: 890, category: 'Frontend', icon: 'compbib',
    features: ['Modal, Drawer, Toast', 'Stepper, Slider, Switch', 'Date-Picker, Combobox', 'Storybook + Tests', 'Accessible'],
    devInstructions: 'Baue 15 zusaetzliche, voll accessible UI-Komponenten (Modal, Drawer, Toast, Stepper, Slider, Switch, Date-Picker, Combobox, ...) mit Storybook und Tests.',
    estimatedHours: 28, tags: ['components', 'library'] },

  // ─────────────────────────── BACKEND — ERWEITERT ───────────────────────────
  { id: 'search-engine', name: 'Search-Engine', description: 'Meilisearch oder Elasticsearch Setup', price: 890, category: 'Backend', icon: 'searchbe',
    features: ['Meilisearch / ES', 'Typo-Tolerant', 'Faceted Search', 'Highlighting', 'Sync-Pipeline'],
    devInstructions: 'Setze Meilisearch oder Elasticsearch auf, mit Typo-Tolerance, Faceted Search, Highlighting und einer Sync-Pipeline aus der Hauptdatenbank.',
    estimatedHours: 22, tags: ['search', 'meilisearch'] },
  { id: 'multi-tenancy', name: 'Multi-Tenancy', description: 'Workspace/Org-Modell mit Isolation', price: 1290, category: 'Backend', icon: 'tenant',
    features: ['Workspace-Modell', 'Row-Level-Isolation', 'Per-Tenant-Branding', 'Quota pro Tenant', 'Admin-Tools'],
    devInstructions: 'Implementiere Multi-Tenancy mit Workspace-Modell, Row-Level-Isolation via RLS, Per-Tenant-Branding, Quota-System und Admin-Tools.',
    estimatedHours: 38, tags: ['tenancy', 'saas'] },
  { id: 'api-gateway', name: 'API-Gateway', description: 'Zentrales Routing + Auth + Throttling', price: 990, category: 'Backend', icon: 'gateway',
    features: ['Routing-Layer', 'Auth-Forwarding', 'Rate-Limit zentral', 'API-Keys', 'Usage-Tracking'],
    devInstructions: 'Baue ein API-Gateway mit zentralem Routing, Auth-Forwarding, zentralem Rate-Limit, API-Keys und Usage-Tracking pro Key.',
    estimatedHours: 26, tags: ['gateway', 'api'] },
  { id: 'realtime-sync', name: 'Real-time Data Sync', description: 'Live-Updates ohne Refresh', price: 690, category: 'Backend', icon: 'rtsync',
    features: ['Supabase Realtime / Pusher', 'Optimistic Updates', 'Conflict-Resolution', 'Presence', 'Reconnect-Logic'],
    devInstructions: 'Integriere Real-time Data Sync (Supabase Realtime oder Pusher) mit Optimistic Updates, Conflict-Resolution, Presence und Reconnect-Logic.',
    estimatedHours: 18, tags: ['realtime', 'sync'] },
  { id: 'migrations', name: 'Migrations-Tool', description: 'Versionierte DB-Migrationen', price: 390, category: 'Backend', icon: 'migration',
    features: ['Reversible Migrations', 'Seed-Skripte', 'Branch-Per-Feature', 'CI-Integration', 'Schema-Diff'],
    devInstructions: 'Setze ein versioniertes Migrations-Tool (Drizzle/Prisma) mit Reversible Migrations, Seed-Skripten, Branch-per-Feature und CI-Integration.',
    estimatedHours: 8, tags: ['migrations', 'db'] },

  // ─────────────────────────── AI — ERWEITERT ───────────────────────────
  { id: 'sentiment', name: 'Sentiment-Analysis', description: 'Stimmungsanalyse für Reviews/Kommentare', price: 590, category: 'AI', icon: 'sent',
    features: ['Multi-Sprache', 'Echtzeit-API', 'Aspekt-basiert', 'Trend-Tracking', 'Dashboard'],
    devInstructions: 'Implementiere Sentiment-Analysis fuer Reviews und Kommentare mit Multi-Sprache, Aspekt-basierter Bewertung, Trend-Tracking und Dashboard.',
    estimatedHours: 14, tags: ['nlp', 'sentiment'] },
  { id: 'ocr', name: 'OCR (Text aus Bildern)', description: 'Texterkennung für Belege/Dokumente', price: 490, category: 'AI', icon: 'ocr',
    features: ['GPT-4 Vision / Tesseract', 'Beleg-Extraktion', 'Tabellen-Erkennung', 'Mehrsprachig', 'Confidence-Score'],
    devInstructions: 'Integriere OCR via GPT-4 Vision oder Tesseract fuer Beleg-Extraktion, Tabellen-Erkennung mit Confidence-Score und mehrsprachiger Unterstuetzung.',
    estimatedHours: 12, tags: ['ocr', 'vision'] },
  { id: 'ai-summarize', name: 'AI-Summarizer', description: 'Lange Texte und Meetings zusammenfassen', price: 490, category: 'AI', icon: 'sum',
    features: ['Multi-Doc-Summary', 'Bullet-Points', 'Action-Items', 'Meeting-Notes', 'API-Endpoint'],
    devInstructions: 'Baue einen AI-Summarizer der lange Texte und Meeting-Transkripte zusammenfasst, Bullet-Points und Action-Items extrahiert.',
    estimatedHours: 10, tags: ['llm', 'summary'] },
  { id: 'ai-code-review', name: 'AI Code-Review-Bot', description: 'GitHub-PR-Reviews durch AI', price: 990, category: 'AI', icon: 'cr',
    features: ['GitHub-App', 'Inline-Comments', 'Best-Practice-Checks', 'Bug-Spotting', 'Custom-Rules'],
    devInstructions: 'Baue einen AI Code-Review-Bot als GitHub-App, der Pull Requests auf Best Practices prueft, Bugs spottet und Custom-Rules respektiert.',
    estimatedHours: 28, tags: ['ai', 'devtools'] },
  { id: 'voice-assistant', name: 'Voice-Assistant', description: 'Sprachgesteuerter App-Assistant', price: 1290, category: 'AI', icon: 'voiceasst',
    features: ['Wake-Word', 'Intent-Routing', 'TTS + STT', 'Action-Execution', 'Multi-Sprachen'],
    devInstructions: 'Baue einen Voice-Assistant mit Wake-Word, Intent-Routing zu App-Actions, TTS+STT-Pipeline und Multi-Sprache-Support.',
    estimatedHours: 36, tags: ['voice', 'assistant'] },

  // ─────────────────────────── MARKETING — ERWEITERT ───────────────────────────
  { id: 'drip-campaign', name: 'Email-Drip-Campaign', description: 'Mehrwöchige Onboarding-Sequenz', price: 590, category: 'Marketing', icon: 'drip',
    features: ['7-Email-Sequenz', 'Verhaltens-Trigger', 'Personalisierung', 'A/B-Test pro Email', 'Reporting'],
    devInstructions: 'Erstelle eine 7-Email Drip-Campaign mit Verhaltens-Triggern, Personalisierung, A/B-Tests pro Email und Reporting.',
    estimatedHours: 16, tags: ['email', 'drip'] },
  { id: 'loyalty', name: 'Loyalty-Programm', description: 'Punkte-System mit Belohnungen', price: 990, category: 'Marketing', icon: 'loyalty',
    features: ['Punkte-System', 'Reward-Tiers', 'Vouchers', 'Mobile-Push', 'Analytics'],
    devInstructions: 'Implementiere ein Loyalty-Programm mit Punkte-System, Reward-Tiers, Vouchers, Mobile-Push-Reminder und detaillierten Analytics.',
    estimatedHours: 26, tags: ['loyalty', 'rewards'] },
  { id: 'push-marketing', name: 'Push-Marketing', description: 'Segmentierte Push-Kampagnen', price: 590, category: 'Marketing', icon: 'pushmkt',
    features: ['Segmentierung', 'Schedule + Trigger', 'Rich-Media', 'A/B-Testing', 'Conversion-Tracking'],
    devInstructions: 'Baue Push-Marketing mit Segmentierung, geplanten und getriggerten Kampagnen, Rich-Media, A/B-Tests und Conversion-Tracking.',
    estimatedHours: 16, tags: ['push', 'marketing'] },
  { id: 'influencer', name: 'Influencer-Tracking', description: 'Custom Codes + Analytics pro Kreator', price: 690, category: 'Marketing', icon: 'inf',
    features: ['Personal Codes', 'Tracking-Links', 'Auszahlungs-Mgmt', 'Performance-Dashboard', 'Vertrags-Mgmt'],
    devInstructions: 'Implementiere Influencer-Tracking mit personalisierten Codes, Tracking-Links, Auszahlungs-Mgmt und Performance-Dashboard pro Kreator.',
    estimatedHours: 22, tags: ['influencer', 'tracking'] },
  { id: 'survey', name: 'Survey & Feedback-Tool', description: 'NPS + Custom Surveys', price: 490, category: 'Marketing', icon: 'survey',
    features: ['NPS', 'Custom-Surveys', 'Conditional Logic', 'Analytics', 'Slack-Integration'],
    devInstructions: 'Baue ein Survey-Tool mit NPS, Custom-Surveys, Conditional Logic, Analytics und Slack-Integration fuer Notifications.',
    estimatedHours: 14, tags: ['survey', 'nps'] },

  // ─────────────────────────── E-COMMERCE — ERWEITERT ───────────────────────────
  { id: 'wishlist', name: 'Wishlist', description: 'Produkte für später speichern', price: 290, category: 'E-Commerce', icon: 'wish',
    features: ['Multi-List', 'Sharing', 'Preis-Drop-Alerts', 'Persistent', 'Sync'],
    devInstructions: 'Implementiere eine Wishlist mit Multi-List-Support, Sharing-Funktion, Preis-Drop-Alerts und Cross-Device-Sync.',
    estimatedHours: 8, tags: ['wishlist', 'shop'] },
  { id: 'reviews', name: 'Produkt-Reviews', description: 'Bewertungen mit Foto-Uploads', price: 590, category: 'E-Commerce', icon: 'review',
    features: ['1-5 Sterne', 'Foto-Upload', 'Verifizierte Käufer', 'Moderation', 'Hilfreich-Voting'],
    devInstructions: 'Baue ein Produkt-Review-System mit 1-5 Sternen, Foto-Uploads, Verifizierte-Kaeufer-Badge, Moderation und Hilfreich-Voting.',
    estimatedHours: 18, tags: ['reviews', 'ugc'] },
  { id: 'subs-mgmt', name: 'Abo-Management Self-Service', description: 'Kunden verwalten Abos selbst', price: 590, category: 'E-Commerce', icon: 'submgt',
    features: ['Pause/Resume', 'Plan-Wechsel', 'Skip-Lieferung', 'Adress-Aenderung', 'Cancellation-Flow'],
    devInstructions: 'Baue ein Self-Service-Abo-Management mit Pause/Resume, Plan-Wechsel, Skip-Lieferung, Adress-Aenderung und sanftem Cancellation-Flow.',
    estimatedHours: 16, tags: ['subscriptions', 'self-service'] },
  { id: 'returns', name: 'Returns-Handling', description: 'Retouren-Portal für Kunden', price: 690, category: 'E-Commerce', icon: 'return',
    features: ['Self-Service-Portal', 'Auto-Label', 'Refund-Workflow', 'Restocking', 'Reason-Analytics'],
    devInstructions: 'Implementiere ein Retouren-Portal mit Self-Service, automatischer Label-Generierung, Refund-Workflow, Restocking und Reason-Analytics.',
    estimatedHours: 18, tags: ['returns', 'logistics'] },
  { id: 'marketplace', name: 'Multi-Vendor-Marketplace', description: 'Mehrere Verkäufer auf einer Plattform', price: 1990, category: 'E-Commerce', icon: 'marketplace',
    features: ['Vendor-Onboarding', 'Provisions-System', 'Split-Payments via Stripe', 'Vendor-Dashboard', 'Payout-Automation'],
    devInstructions: 'Baue einen Multi-Vendor-Marketplace mit Vendor-Onboarding, Provisions-System, Stripe-Split-Payments, Vendor-Dashboard und automatisierten Auszahlungen.',
    estimatedHours: 60, tags: ['marketplace', 'multi-vendor'] },

  // ─────────────────────────── ANALYTICS — ERWEITERT ───────────────────────────
  { id: 'ab-dashboard', name: 'A/B-Test-Dashboard', description: 'Auswertung aller Experimente', price: 590, category: 'Analytics', icon: 'abdash',
    features: ['Experiment-Liste', 'Signifikanz-Test', 'Lift-Anzeige', 'Cohort-Filter', 'Export'],
    devInstructions: 'Erstelle ein A/B-Test-Dashboard mit Experiment-Liste, Signifikanz-Tests, Lift-Anzeige, Cohort-Filtern und Export.',
    estimatedHours: 16, tags: ['ab-test', 'dashboard'] },
  { id: 'report-builder', name: 'Custom Report-Builder', description: 'Drag & Drop Reports erstellen', price: 990, category: 'Analytics', icon: 'rb',
    features: ['Drag-Drop-Builder', 'Custom-Metriken', 'Scheduled Send', 'Sharing', 'Templates'],
    devInstructions: 'Baue einen Custom Report-Builder mit Drag-Drop-Komponenten, eigenen Metriken, Scheduled-Send und Sharing.',
    estimatedHours: 28, tags: ['reports', 'builder'] },
  { id: 'cohort', name: 'Cohort-Analyse', description: 'Retention nach Acquisition-Cohort', price: 590, category: 'Analytics', icon: 'cohort',
    features: ['Retention-Heatmap', 'Custom-Cohorts', 'Pro-Channel-Vergleich', 'Drill-Down', 'Export'],
    devInstructions: 'Implementiere Cohort-Analyse mit Retention-Heatmap, Custom-Cohort-Definition, Pro-Channel-Vergleich, Drill-Down und Export.',
    estimatedHours: 16, tags: ['cohort', 'retention'] },
  { id: 'revenue', name: 'Revenue-Analytics', description: 'MRR, ARR, Churn, LTV im Detail', price: 690, category: 'Analytics', icon: 'rev',
    features: ['MRR/ARR', 'Churn-Tracking', 'Expansion-Revenue', 'LTV-Berechnung', 'Forecasting'],
    devInstructions: 'Baue Revenue-Analytics mit MRR/ARR-Tracking, Churn-Detection, Expansion-Revenue, LTV-Berechnung und einfachem Forecasting.',
    estimatedHours: 18, tags: ['revenue', 'saas'] },
  { id: 'ltv', name: 'Customer-Lifetime-Value', description: 'CLV-Berechnung mit Segmenten', price: 490, category: 'Analytics', icon: 'ltv',
    features: ['CLV-Berechnung', 'Pro-Segment', 'Predictive CLV', 'Channel-Attribution', 'Visualisierung'],
    devInstructions: 'Implementiere Customer-Lifetime-Value pro Segment mit Predictive CLV, Channel-Attribution und klaren Visualisierungen.',
    estimatedHours: 14, tags: ['clv', 'analytics'] },

  // ─────────────────────────── MOBILE — ERWEITERT ───────────────────────────
  { id: 'apple-signin', name: 'Sign in with Apple', description: 'Native Apple-Login (iOS-Pflicht)', price: 290, category: 'Mobile', icon: 'apple',
    features: ['Native iOS', 'Hide-Email-Option', 'Server-Verifikation', 'Token-Refresh', 'App-Review-konform'],
    devInstructions: 'Integriere Sign in with Apple mit nativem iOS-Flow, Hide-Email-Support, Server-Verifikation und Token-Refresh.',
    estimatedHours: 8, tags: ['apple', 'auth'] },
  { id: 'shortcuts', name: 'App-Shortcuts (Siri)', description: 'iOS-Shortcuts + Quick-Actions', price: 390, category: 'Mobile', icon: 'shortcut',
    features: ['Siri-Intents', 'Quick-Actions', 'Spotlight-Search', 'Action-Donate', 'Personalisiert'],
    devInstructions: 'Implementiere iOS App-Shortcuts mit Siri-Intents, 3D-Touch Quick-Actions, Spotlight-Search-Indexing und Action-Donations.',
    estimatedHours: 12, tags: ['siri', 'shortcuts'] },
  { id: 'widgets', name: 'iOS + Android Widgets', description: 'Home-Screen-Widgets', price: 590, category: 'Mobile', icon: 'widget',
    features: ['iOS WidgetKit', 'Android Glance', 'Multiple Sizes', 'Live-Update', 'Deep-Link-In'],
    devInstructions: 'Baue Home-Screen-Widgets fuer iOS (WidgetKit) und Android (Glance) in mehreren Groessen mit Live-Updates und Deep-Link-In-App.',
    estimatedHours: 18, tags: ['widgets', 'mobile'] },
  { id: 'wear', name: 'Apple Watch / Wear OS', description: 'Companion-App für Wearables', price: 990, category: 'Mobile', icon: 'wear',
    features: ['watchOS App', 'Wear OS App', 'Complications', 'Health-Sync', 'Independent-Mode'],
    devInstructions: 'Baue eine Companion-App fuer Apple Watch (watchOS) und Wear OS mit Complications, Health-Sync und Independent-Mode.',
    estimatedHours: 32, tags: ['watch', 'wearable'] },
  { id: 'ar', name: 'AR-Integration', description: 'ARKit + ARCore für Produkt-Vorschau', price: 1490, category: 'Mobile', icon: 'ar',
    features: ['ARKit (iOS)', 'ARCore (Android)', '3D-Modell-Loading', 'Plane-Detection', 'Snapshot-Sharing'],
    devInstructions: 'Integriere AR via ARKit und ARCore fuer Produkt-Vorschau mit 3D-Modellen, Plane-Detection und Snapshot-Sharing.',
    estimatedHours: 38, tags: ['ar', 'mobile'] },

  // ─────────────────────────── DEVOPS — ERWEITERT ───────────────────────────
  { id: 'docker', name: 'Container-Setup (Docker/K8s)', description: 'Containerisierung + Orchestrierung', price: 990, category: 'DevOps', icon: 'docker',
    features: ['Multi-Stage-Dockerfile', 'docker-compose Dev', 'K8s-Manifeste', 'Secrets-Mgmt', 'Health-Checks'],
    devInstructions: 'Containerisiere die App mit Multi-Stage-Dockerfile, docker-compose fuer Dev, Kubernetes-Manifesten und Secrets-Management.',
    estimatedHours: 22, tags: ['docker', 'k8s'] },
  { id: 'iac', name: 'Infrastructure-as-Code', description: 'Terraform für gesamte Infra', price: 1290, category: 'DevOps', icon: 'iac',
    features: ['Terraform-Modules', 'Multi-Env (dev/prod)', 'State-Backend', 'CI-Integration', 'Doku'],
    devInstructions: 'Definiere die gesamte Infrastruktur als Terraform-Code mit Modules, Multi-Env, Remote-State-Backend, CI-Integration und vollstaendiger Doku.',
    estimatedHours: 32, tags: ['terraform', 'iac'] },
  { id: 'db-replication', name: 'Database-Replikation', description: 'Read-Replicas + Failover', price: 690, category: 'DevOps', icon: 'rep',
    features: ['Read-Replicas', 'Auto-Failover', 'Lag-Monitoring', 'Connection-Pooling', 'Restore-Tests'],
    devInstructions: 'Setze Database-Replikation mit Read-Replicas, Auto-Failover, Lag-Monitoring, Connection-Pooling (PgBouncer) und Restore-Tests.',
    estimatedHours: 18, tags: ['db', 'replication'] },
  { id: 'perf-opt', name: 'Performance-Optimierung', description: 'Lighthouse 95+ + Backend-Tuning', price: 990, category: 'DevOps', icon: 'perf',
    features: ['Lighthouse 95+', 'Bundle-Analyse', 'Image-Opt', 'DB-Query-Tuning', 'Caching-Strategie'],
    devInstructions: 'Optimiere die Performance auf Lighthouse 95+, analysiere Bundle, optimiere Bilder, tune DB-Queries und etabliere Caching-Strategie.',
    estimatedHours: 26, tags: ['performance', 'optimization'], popular: true },
  { id: 'migration', name: 'Server-Migration', description: 'Umzug zu neuer Plattform mit Zero-Downtime', price: 1490, category: 'DevOps', icon: 'mig',
    features: ['Zero-Downtime', 'DNS-Cutover', 'Daten-Migration', 'Rollback-Plan', 'Smoke-Tests'],
    devInstructions: 'Migriere die Server zu einer neuen Plattform mit Zero-Downtime, DNS-Cutover-Strategie, Daten-Migration, Rollback-Plan und Smoke-Tests.',
    estimatedHours: 36, tags: ['migration', 'devops'] },

  // ─────────────────────────── SECURITY — ERWEITERT ───────────────────────────
  { id: 'soc2', name: 'SOC 2 / ISO 27001 Audit', description: 'Compliance-Vorbereitung mit Maßnahmen', price: 2490, category: 'Security', icon: 'soc2',
    features: ['Gap-Analyse', 'Policy-Templates', 'Tech-Implementierung', 'Audit-Begleitung', 'Vanta/Drata-Setup'],
    devInstructions: 'Bereite SOC 2 oder ISO 27001 Audit vor: Gap-Analyse, Policy-Templates, technische Massnahmen, Vanta/Drata-Integration und Audit-Begleitung.',
    estimatedHours: 60, tags: ['compliance', 'soc2'] },
  { id: 'rate-pro', name: 'Rate-Limiting Pro', description: 'Mehrstufige API-Schutz-Strategie', price: 590, category: 'Security', icon: 'ratepro',
    features: ['Per-Route-Limits', 'IP + User Combo', 'Distributed Limits', 'Bypass-Token', 'Reporting'],
    devInstructions: 'Implementiere mehrstufiges Rate-Limiting mit Per-Route-Limits, IP+User-Kombi, distributed Limits via Redis, Bypass-Tokens und Reporting.',
    estimatedHours: 14, tags: ['rate-limit', 'security'] },
  { id: 'captcha', name: 'CAPTCHA-Integration', description: 'Cloudflare Turnstile / hCaptcha', price: 290, category: 'Security', icon: 'captcha',
    features: ['Cloudflare Turnstile', 'Adaptive Challenges', 'Server-Verifikation', 'Bot-Score', 'A11y-konform'],
    devInstructions: 'Integriere Cloudflare Turnstile (oder hCaptcha) mit adaptiven Challenges, Server-Verifikation, Bot-Score-Auswertung und A11y-konformer UI.',
    estimatedHours: 6, tags: ['captcha', 'bot' ] },
  { id: 'vuln-scan', name: 'Vulnerability-Scanning', description: 'Automatisches Dependency + Container Scanning', price: 590, category: 'Security', icon: 'scan',
    features: ['Snyk / Dependabot', 'Container-Scan', 'CI-Integration', 'Auto-PRs', 'CVE-Alerts'],
    devInstructions: 'Setze Vulnerability-Scanning via Snyk oder Dependabot fuer Dependencies + Container, Auto-PRs fuer Patches und CVE-Alerts in Slack.',
    estimatedHours: 8, tags: ['vulnerability', 'scanning'] },
  { id: 'kyc', name: 'Identity-Verification (KYC)', description: 'ID-Verifikation für regulierte Geschäfte', price: 990, category: 'Security', icon: 'kyc',
    features: ['Sumsub / Veriff', 'ID + Selfie-Check', 'Sanctions-Listen', 'AML-Workflow', 'Auto-Approval'],
    devInstructions: 'Integriere Identity-Verification via Sumsub oder Veriff mit ID + Selfie-Check, Sanctions-Listen, AML-Workflow und Auto-Approval-Rules.',
    estimatedHours: 22, tags: ['kyc', 'aml'] },
]
